### ISSUE TITLE
max_length does not work in Fields

### ISSUE THREAD

**Issue by yudjinn** [tiangolo/sqlmodel#126]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from sqlmodel import SQLModel, Field


class Locations(SQLModel, table=True):
    LocationName: str = Field(max_length=255)
```

### Description

When running the above code, I get a
 `ValueError: On field "LocationName" the following field constraints are set but not enforced: max_length` 

I also tried pydantic's documentation by changing the 'str' typing to `constr(max_length=255)` to no avail.

### Operating System

Windows

### SQLModel Version

0.0.4

### Python Version

3.9.4

**Comment by yudjinn** [comment]
This started working for some reason, genuinely not sure what resolved; maybe new version  of fastapi?

**Comment by yasamoka** [comment]
How is it even related to FaatAPI? SQLModel is still at version 0.0.4.

**Comment by PaleNeutron** [comment]
2 years passed, is There any official solution?
