### ISSUE TITLE
Best practice for multiple update

### ISSUE THREAD

**Issue by hilmanski** [tiangolo/sqlmodel#181]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Example code multiple update data


def update_heroes():
    with Session(engine) as session:
         statement = select(Hero).where(Hero.name == "Spider-Boy")  # 
        results = session.exec(statement)  # 
        hero_1 = results.one()  # 
        print("Hero 1:", hero_1)  # 
        statement = select(Hero).where(Hero.name == "Captain North America")  # 
        results = session.exec(statement)  #         
        hero_2 = results.one()  # 
 .....
```

### Description

Based on the documentation, when we want to update multiple data. We need to do N+1 query:
[doc multiple update](https://sqlmodel.tiangolo.com/tutorial/update/#multiple-updates)

Are there any other way to do it with only select needed data once?

### Operating System

macOS

### SQLModel Version

0.0.4

### Python Version

3.9

**Comment by aminalaee** [comment]
@hilmanski Do you mean you want to do a bulk update?

If that's the case I think an `update` method would be needed the same as `select`, something like this maybe:

```python
statement = update(Hero).update(Hero.name == "Spider").where(Hero.name == "Spider-Boy")
number_of_modified = session.exec(statement)  # UPDATE hero SET name = 'Spider' WHERE name = 'Spider-Boy'
```

I think that's also the case for bulk delete, as of now I can see only single object-level deletes.
If @tiangolo confirms I can work on them.

**Comment by johnziebro** [comment]
@hilmanski  Could use improvement, but for those who are looking for a [bulk update function](https://github.com/tiangolo/sqlmodel/issues/59#issuecomment-1111675589) until SQLModel gets its own.

**Comment by fredrikaverpil** [comment]
Any news on this?

It seems very inefficient to select for each update when you have a large number of entities to update. 

Has there been no efforts to solve this in 8 months?

**Comment by tiangolo** [comment]
@hilmanski Your code example doesn't include any update, so I'm not sure I understand the question. But changes are sent to the DB on `session.commit()`, not before.

Also, as all the work is really done by SQLAlchemy, you can apply here the same solutions you could find there.

**Comment by Yangeok** [comment]
Any update about multiple update feature?

**Comment by dev-bilal-raza** [comment]
Hey @tiangolo @Yangeok,

I have created a function that can update multiple fields, please check function below ⬇️.

```python
from typing import Dict, Any
from app.db.db_utils import DB_SESSION
from app.models.user_models import User
from app.utils.api_messages import MESSAGES
from app.utils.api_statuses import STATUS


class UserInUpdate(BaseModel):
    username: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None
   

def update_user(user_id: int, user_details: UserInUpdate, db: DB_SESSION) -> Dict[str, Any]:
        # Fetch the user by id
        user = db.get(user, user_id)
        if not user:
            return {
                "status": STATUS["NOT_FOUND"],
                "message": MESSAGES["NOT_FOUND_MESSAGE"]
            }
        
        # update user fields with provided details
        user_to_update = user_details.model_dump(exclude_unset=True)
        for key, value in user_to_update.items():
            setattr(user, key, value)
        
        # commit changes to the database
        db.add(user)
        db.commit()
        db.refresh(user)
        
        return {
            "status": STATUS["SUCCESS"],
            "message": "User updated successfully",
            "updated_user": user
        }
```

Here's a step-by-step explanation:

- The function first attempts to fetch the user by their ID using `db.get(User, user_id)`.
- If the user is not found, it returns a status of `NOT_FOUND` with an appropriate message.
- If the user is found, it updates the user's fields with the provided details from `user_details`. Only the fields that are set in `user_details` will be updated, thanks to the [exclude_unset=True](https://fastapi.tiangolo.com/tutorial/body-updates/#using-pydantics-exclude_unset-parameter) parameter.
- The updated user object is then added to the database session, and the changes are committed.
- The function refreshes the user object to reflect the latest state from the database.
- Finally, it returns a success status along with the updated user object.

**Comment by Nikola-Milovic** [comment]
Since `session.execute` is deprecated now, what is the current alternative to 

```
 stmt = (
     update(sop_model.Model)
    .where(sop_model.Model.id == model.id)
     .values(...)
)
await session.execute(stmt)
```

I do not want to fetch the model then `session.add` it, I just want to update it

**Comment by mikeedjones** [comment]
I think you just need to add the values as the `params` kwarg:

```python 
 stmt = (
     update(sop_model.Model)
    .where(sop_model.Model.id == model.id)
)
session.exec(stmt, params=[val.model_dump() for val in values])
```

The params need to be accessible by key.
