### ISSUE TITLE
I18N Internationalization

### ISSUE THREAD

**Issue by masreplay** [tiangolo/sqlmodel#210]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
def get_locale():
    return 'fi'


translation_hybrid = TranslationHybrid(
    current_locale=get_locale,
    default_locale='en'
)


class TeacherBase(SQLModel):
    ar_name: Optional[Any] = Field(sa_column=Column(HSTORE))
    name: str = Field(sa_column=translation_hybrid(ar_name))
```

### Description

translate key in the database 

### Wanted Solution

I want to translate filed in data base using store pg extension or any other way if it's possibledatabase

### Wanted Code

```python
don't know!
```

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

Python 3.9.7

**Comment by bvsn** [comment]
@masreplay any updates during the year? 🤔 Did you find a solution?

**Comment by masreplay** [comment]
Yes i found one, i stopped using fastapi and using nest instead

**Comment by bvsn** [comment]
Maybe it will be useful for someone who is passing through the issue. I've made a very rude adoption of `hybrid_property` i18n approach through the SQLModel `Field`:

```
class SaTranslationFieldComparator(types.TypeEngine.Comparator):
    def __eq__(self, other: Any) -> bool:
        return self.op("->> 'en' =")(other)


class SaTranslationField(types.TypeDecorator):
    impl: JSON = JSON()
    cache_ok = True
    comparator_factory = SaTranslationFieldComparator

    def coerce_compared_value(self, op: Any, value: Any) -> types.TypeEngine[Any]:
        return self.impl.coerce_compared_value(op, value)

    def process_bind_param(self, value: Any, dialect: Any) -> Optional[dict]:  # type: ignore
        if value is None:
            return None

        return {"en": value}

    def process_result_value(self, value: Any, dialect: Any) -> Optional[Any]:
        translated = value.get("en")
        return translated


def TranslationField(**kwargs: Any) -> Any:
    return Field(sa_column=Column(SaTranslationField), nullable=False, default=dict(), **kwargs)
```

Usage:
```
name: str = TranslationField()
```

In your alembic create an appropriate Column in the Database:
```
sa.Column("name", SaTranslationField, nullable=False, server_default="{}"),
```
