### ISSUE TITLE
How do I integrate or use SQLModel with Pandas?

### ISSUE THREAD

**Issue by iudeen** [tiangolo/sqlmodel#215]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import pandas as pd


jobs_df = pd.read_csv('data/nyc-jobs.csv')

# SQL Model starts from here
```

### Description

I would like to ingest Pandas DataFrame to SQL using the SQLModel. I also would like to retrieve data back using Pandas and SQLModel. Is there a way for it?

### Operating System

Linux, Windows

### SQLModel Version

0.0.6

### Python Version

3.9

**Comment by SamEdwardes** [comment]
Pandas has a helpful method [`pandas.DataFrame.from_records()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_records.html), and SQLModel has a method `SQLModel.dict()`. 

Here is an example of how you could use it with SQLModel

```python
from typing import List, Optional

import pandas as pd
from sqlmodel import Field, SQLModel


class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    email: str
    password: str
    name: str
    

# Create a few users for example
users = [
    User(email="sam@gmail.com", password="1234", name="sam"),
    User(email="jake@gmail.com", password="abcd", name="jake"),
    User(email="olivia@gmail.com", password="password", name="olivia"),
]


def sqmodel_to_df(objs: List[SQLModel]) -> pd.DataFrame:
    """Convert a SQLModel objects into a pandas DataFrame."""
    records = [i.dict() for i in objs]
    df = pd.DataFrame.from_records(records)
    return df

df = sqmodel_to_df(users)
print(df)

#      id             email  password    name
# 0  None     sam@gmail.com      1234     sam
# 1  None    jake@gmail.com      abcd    jake
# 2  None  olivia@gmail.com  password  Olivia
```

**Comment by iudeen** [comment]
> Pandas has a helpful method [`pandas.DataFrame.from_records()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_records.html), and SQLModel has a method `SQLModel.dict()`. 
> 
> Here is an example of how you could use it with SQLModel
> 
> ```python
> from typing import List, Optional
> 
> import pandas as pd
> from sqlmodel import Field, SQLModel
> 
> 
> class User(SQLModel, table=True):
>     id: Optional[int] = Field(default=None, primary_key=True)
>     email: str
>     password: str
>     name: str
>     
> 
> # Create a few users for example
> users = [
>     User(email="sam@gmail.com", password="1234", name="sam"),
>     User(email="jake@gmail.com", password="abcd", name="jake"),
>     User(email="olivia@gmail.com", password="password", name="olivia"),
> ]
> 
> 
> def sqmodel_to_df(objs: List[SQLModel]) -> pd.DataFrame:
>     """Convert a SQLModel objects into a pandas DataFrame."""
>     records = [i.dict() for i in objs]
>     df = pd.DataFrame.from_records(records)
>     return df
> 
> df = sqmodel_to_df(users)
> print(df)
> 
> #      id             email  password    name
> # 0  None     sam@gmail.com      1234     sam
> # 1  None    jake@gmail.com      abcd    jake
> # 2  None  olivia@gmail.com  password  Olivia
> ```

Thanks, this suffices the SQLModel to Pandas df. 

Is there a way we could use `DataFrame.to_sql()` to ingest data?

**Comment by SamEdwardes** [comment]
Hi @iudeen, I am not sure I follow what you are looking for. Is the idea to convert a `pandas.DataFrame` to SQLModel objects without using a for loop? If you just want to send an existing `pandas.DataFrame` to a SQL database I think [`pandas.DataFrame.to_sql`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) already does that.

**Comment by SamEdwardes** [comment]
If you want to convert a DataFrame back to a list of SQLModel objects you could do this.

```python
from typing import List, Optional

import pandas as pd
from sqlmodel import Field, SQLModel


class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    email: str
    password: str
    name: str
    

# Create a few users for example
users = [
    User(email="sam@gmail.com", password="1234", name="sam"),
    User(email="jake@gmail.com", password="abcd", name="jake"),
    User(email="olivia@gmail.com", password="password", name="olivia"),
]


def sqmodel_to_df(objs: List[SQLModel]) -> pd.DataFrame:
    """Convert a SQLModel objects into a pandas DataFrame."""
    records = [i.dict() for i in objs]
    df = pd.DataFrame.from_records(records)
    return df

df = sqmodel_to_df(users)
print(df)

#      id             email  password    name
# 0  None     sam@gmail.com      1234     sam
# 1  None    jake@gmail.com      abcd    jake
# 2  None  olivia@gmail.com  password  Olivia

def df_to_sqlmodel(df: pd.DataFrame) -> List[SQLModel]:
    """Convert a pandas DataFrame into a a list of SQLModel objects."""    
    objs = [User(**row) for row in df.to_dict('records')]
    return objs

sql_model_objs = df_to_sqlmodel(df)
for i in sql_model_objs:
    print(i)
    
# id=None email='sam@gmail.com' password='1234' name='sam'
# id=None email='jake@gmail.com' password='abcd' name='jake'
# id=None email='olivia@gmail.com' password='password' name='olivia'
```

Not sure how to do this without a loop of some kind. Maybe you could come up with something that uses `pandas.DataFrame.apply()` but I am not sure if that would be faster than the list comprehension in my example.

**Comment by iudeen** [comment]
> If you want to convert a DataFrame back to a list of SQLModel objects you could do this.
> 
> ```python
> from typing import List, Optional
> 
> import pandas as pd
> from sqlmodel import Field, SQLModel
> 
> 
> class User(SQLModel, table=True):
>     id: Optional[int] = Field(default=None, primary_key=True)
>     email: str
>     password: str
>     name: str
>     
> 
> # Create a few users for example
> users = [
>     User(email="sam@gmail.com", password="1234", name="sam"),
>     User(email="jake@gmail.com", password="abcd", name="jake"),
>     User(email="olivia@gmail.com", password="password", name="olivia"),
> ]
> 
> 
> def sqmodel_to_df(objs: List[SQLModel]) -> pd.DataFrame:
>     """Convert a SQLModel objects into a pandas DataFrame."""
>     records = [i.dict() for i in objs]
>     df = pd.DataFrame.from_records(records)
>     return df
> 
> df = sqmodel_to_df(users)
> print(df)
> 
> #      id             email  password    name
> # 0  None     sam@gmail.com      1234     sam
> # 1  None    jake@gmail.com      abcd    jake
> # 2  None  olivia@gmail.com  password  Olivia
> 
> def df_to_sqlmodel(df: pd.DataFrame) -> List[SQLModel]:
>     """Convert a pandas DataFrame into a a list of SQLModel objects."""    
>     objs = [User(**row) for row in df.to_dict('records')]
>     return objs
> 
> sql_model_objs = df_to_sqlmodel(df)
> for i in sql_model_objs:
>     print(i)
>     
> # id=None email='sam@gmail.com' password='1234' name='sam'
> # id=None email='jake@gmail.com' password='abcd' name='jake'
> # id=None email='olivia@gmail.com' password='password' name='olivia'
> ```
> 
> Not sure how to do this without a loop of some kind. Maybe you could come up with something that uses `pandas.DataFrame.apply()` but I am not sure if that would be faster than the list comprehension in my example. 

@SamEdwardes Thanks for your reply! I'll give your suggestions a try. If I find a better way, I'll share it here!

**Comment by johnziebro** [comment]
Came here for the sqmodel_to_df() function, thank you. I found that the created dataframe does not retain the column order, so here is a slight improvement which does using the first object's schema attribute.

``` python
def sqlmodel_to_df(objects: List[SQLModel]) -> pd.DataFrame:
    """Convert a SQLModel objects into a pandas DataFrame.
    Usage
    ----------
    df = sqlmodel_to_df(list_of_sqlmodels)
    Parameters
    ----------
    :param objects: List[SQLModel]: List of objects to be converted."""
    
    records = [obj.dict() for obj in objects]
    df = pd.DataFrame.from_records(records)
    return df[list(objects[0].schema()["properties"].keys())]
```

**Comment by nthomsencph** [comment]
Thanks for the snippets. This will work too

``` python
def sqlmodel_to_df(objects: List[SQLModel]) -> pd.DataFrame:
    """Converts SQLModel objects into a Pandas DataFrame.
    Usage
    ----------
    df = sqlmodel_to_df(list_of_sqlmodels)
    Parameters
    ----------
    :param objects: List[SQLModel]: List of SQLModel objects to be converted.
    """

    return pd.DataFrame.from_records(map(dict, objects)).iloc[:, 1:]
```
Note: the `.iloc[:, 1]` operations gets rid of a column containing SQLmodel objs
