### ISSUE TITLE
SQLAlchemy Error on Many To Many Relationship

### ISSUE THREAD

**Issue by udasitharani** [tiangolo/sqlmodel#243]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import List, Optional
from sqlmodel import Relationship, SQLModel, Field


class UserPostLink:
    user_id: Optional[int] = Field(
        default=None, foreign_key="users.id", primary_key=True
    )
    post_id: Optional[int] = Field(
        default=None, foreign_key="posts.id", primary_key=True
    )

class Users(SQLModel, table=True):
    __table_args__ = (UniqueConstraint("email"),)

    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(index=True)
    name: str
    password: str

    posts: List["Posts"] = Relationship(back_populates="users", link_model=UserPostLink)

class Posts(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    type: str
    post_id: str

    users: List["Users"] = Relationship(back_populates="posts", link_model=UserPostLink)
```

### Description

When I create these models, I get the following error.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/udasitharani/dev/code/later/server/main.py", line 15, in <module>
    from . import constants, models
  File "/Users/udasitharani/dev/code/later/server/models.py", line 14, in <module>
    class Users(SQLModel, table=True):
  File "/Users/udasitharani/dev/code/later/server/venv/lib/python3.10/site-packages/sqlmodel/main.py", line 356, in __init__
    ins = inspect(rel_info.link_model)
  File "/Users/udasitharani/dev/code/later/server/venv/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 71, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'type'>
```

Now my understanding is this is to do with the `link_model` argument passed to `Relationship` since when I remove that argument, my app runs fine. 
On searching Google, I found that similar issue has been faced by people before for other packages on switching to 1.3.15, but SQLModel requires 1.4.17 or above.
My current version of SQLAlchemy is 1.4.31.

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

3.10.2

**Comment by byrman** [comment]
Your link table model seems incomplete. Does `class UserPostLink(SQLModel, table=True):` solve your problem?

**Comment by udasitharani** [comment]
Yep, that seems to be solving it
