### ISSUE TITLE
how to auto generate created_at, updated_at, deleted_at... field with SQLModel

### ISSUE THREAD

**Issue by mr-m0nst3r** [tiangolo/sqlmodel#252]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
> I need some sample codes, thank you
```

### Description

I want to have , let's say, three extra columns for created_time, updated_time, deleted_time, their value are set at different operations, just like the column name suggested.

I'm new to ORM, and SQLAlchemy seems support this function.

How to achieve this using SQLModel?

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

Python 3.9.9

**Comment by byrman** [comment]
You probably want to use a callable here, e.g. `Field(default_factory=datetime.utcnow, nullable=False)`.

**Comment by mr-m0nst3r** [comment]
problem solved, thank you guys

**Comment by facundopadilla** [comment]
it's work for me

```py

from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, SQLModel


class BaseTable(SQLModel):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime(timezone=True), server_default=func.now(), nullable=True
        )
    )
    updated_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime(timezone=True), onupdate=func.now(), nullable=True
        )
    )
```

**Comment by rjpaul2** [comment]
> it's work for me
> 
> ```python
> from datetime import datetime
> from typing import Optional
> 
> from sqlalchemy import Column, DateTime, func
> from sqlmodel import Field, SQLModel
> 
> 
> class BaseTable(SQLModel):
>     id: Optional[int] = Field(default=None, primary_key=True)
>     created_at: Optional[datetime] = Field(
>         sa_column=Column(
>             DateTime(timezone=True), server_default=func.now(), nullable=True
>         )
>     )
>     updated_at: Optional[datetime] = Field(
>         sa_column=Column(
>             DateTime(timezone=True), onupdate=func.now(), nullable=True
>         )
>     )
> ```

I found adding ```default=None``` fixes an issue which required ```created_at``` and ```updated_at``` when using SQLModel `model_validate` . The optimal code is 

`from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, SQLModel


class BaseTable(SQLModel):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), server_default=func.now(), nullable=True
        )
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), onupdate=func.now(), nullable=True
        )
    )`

**Comment by atentoguy** [comment]
Hello @rjpaul2,
I'm trying to use this class as a base for multiple tables in the database and I'm getting the following error.
Have you ever been through this?

raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column object 'created_at' already assigned to Table 'table_test'


```
class BaseTable(SQLModel):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), server_default=func.now(), nullable=True
        )
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), onupdate=func.now(), nullable=True
        )
    )

class TableTest(BaseTable, table=True):
    __tablename__ = "table_test"

class TableTest2(BaseTable, table=True):
    __tablename__ = "table_test2"
```

**Comment by DaanRademaker** [comment]
I have the same issue as atentoguy! Not sure why this is happening either. Would really like this feature

**Comment by atentoguy** [comment]
> I have the same issue as atentoguy! Not sure why this is happening either. Would really like this feature

I found the solution to this problem in [https://github.com/tiangolo/sqlmodel/discussions/743](https://github.com/tiangolo/sqlmodel/discussions/743).

```
class BaseTable(SQLModel):
    id: Optional[int] = Field(default=None, primary_key=True)

    created_at: datetime = Field(
        sa_type=TIMESTAMP(timezone=True),
        sa_column_kwargs={"server_default": text("CURRENT_TIMESTAMP")},
        nullable=False
    )

    updated_at: Optional[datetime] = Field(
        default=None,
        sa_type=TIMESTAMP(timezone=True),
        sa_column_kwargs={"onupdate": func.now(), "nullable": True}
    )
```
Now it is possible to reuse this class in other tables.

**Comment by DaanRademaker** [comment]
Thanks for the reply. For further reference, this works as well which is how I ended up implementing it:

```
from datetime import datetime

import sqlalchemy as sa
from sqlmodel import Field, SQLModel

class SomeBaseModel(SQLModel):
    created_on: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={"server_default": sa.func.now()},
        nullable=False,
    )
    modified_on: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={"onupdate": sa.func.now(), "server_default": sa.func.now()},
    )
```

**Comment by charliejharrison** [comment]
I think you can do this without resorting to `sa_column_kwargs`:

```Python
class TableBase(SQLModel, table=False):
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow, 
                                 onupdate=datetime.utcnow)
```

**Comment by opyate** [comment]
`onupdate` doesn't work, so this is what I have:

```
from datetime import datetime

import sqlalchemy as sa
from pydantic import model_validator
from sqlalchemy.sql import func
from sqlmodel import Field, SQLModel


class TemporalBase(SQLModel):
    created_at: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={"server_default": sa.func.now()},
        nullable=False,
    )
    updated_at: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={
            "server_default": sa.func.now(),
            "onupdate": sa.func.now(),  # onupdate doesn't work: https://github.com/sqlalchemy/sqlalchemy/issues/4652
        },
    )

    @model_validator(mode="after")
    @classmethod
    def update_updated_at(cls, obj: "TemporalBase") -> "TemporalBase":
        """Update updated_at field."""
        # must disable validation to avoid infinite loop
        obj.model_config["validate_assignment"] = False

        # update updated_at field
        obj.updated_at = datetime.now()

        # enable validation again
        obj.model_config["validate_assignment"] = True
        return obj
```

**Comment by Johnb6262** [comment]
I tried what @opyate suggested code above, but it doesn't work, yet.  I don't know what's missing or how the "update_updated_at" method is supposed to be triggered, but it doesn't hit a breakpoint when I run in debug mode when I'm adding new Models to the database.  An explanation of how it's supposed to work to replace or override "onupdate" might help.

Here is my code:

```
@model_validator(mode="after")
    @classmethod
    def update_updated_at(cls, obj: "MetaBase") -> "MetaBase":
        """Update meta_updated_at field."""
        # must disable validation to avoid infinite loop
        obj.model_config["validate_assignment"] = False

        # update meta_updated_at field
        obj.meta_updated_at = datetime.utcnow()

        # re-enable validation again
        obj.model_config["validate_assignment"] = True
        return obj
        ```

**Comment by chenlb** [comment]
mysql onupdate doesn't work.  

https://docs.sqlalchemy.org/en/20/dialects/mysql.html#rendering-on-update-current-timestamp-for-mysql-mariadb-s-explicit-defaults-for-timestamp

code like this, it is work.

```python
# ...
    created_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            server_default=text('CURRENT_TIMESTAMP'),
            nullable=False
        )
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        )
    )
# ...
```

**Comment by tripathyas** [comment]
I am using Postgresql and tried above approach but it did not work for "updated_at" column. I handled it in the database directly:


```
CREATE OR REPLACE FUNCTION update_modified_column() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW; 
END;
$$ language 'plpgsql';



CREATE TRIGGER update_{tablename}_modtime BEFORE UPDATE ON {TABALENAME} FOR EACH ROW EXECUTE PROCEDURE  update_modified_column();

```

**Comment by AythaE** [comment]
Regarding @opyate code, you need to [enable `validate_assignment`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_assignment) so the instances are revalidated in each change and the `updated_at` would be updated.

So the final code would be:
```py
from datetime import datetime

import sqlalchemy as sa
from pydantic import model_validator
from sqlalchemy.sql import func
from sqlmodel import Field, SQLModel


class TemporalBase(SQLModel):
    model_config = ConfigDict(validate_assignment=True)

    created_at: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={"server_default": sa.func.now()},
        nullable=False,
    )
    updated_at: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs={
            "server_default": sa.func.now(),
            "onupdate": sa.func.now(),  # onupdate doesn't work: https://github.com/sqlalchemy/sqlalchemy/issues/4652
        },
    )

    @model_validator(mode="after")
    @classmethod
    def update_updated_at(cls, obj: "TemporalBase") -> "TemporalBase":
        """
        Update updated_at field of an object if it has any value. So the first time will be set by the DB on  
        insert time and the following updates will trigger the updated_at field change.

        :param obj: The object whose updated_at field needs to be updated.
        :return: The updated object.

        """
        # must disable validation to avoid infinite loop
        obj.model_config["validate_assignment"] = False

        if obj.updated_at:
            # update updated_at field
            obj.updated_at = datetime.now()

        # enable validation again
        obj.model_config["validate_assignment"] = True
        return obj
```

**Comment by kimprap** [comment]
For future readers, the "onupdate" takes in a callable, not an object. Here is the setup that worked for me:
```python
  updated_at: datetime | None = Field(
      default_factory=lambda: datetime.now(timezone.utc),
      nullable=False,
      sa_column_kwargs={
          "onupdate": lambda: datetime.now(timezone.utc),
      },
  )
```

**Comment by iloveitaly** [comment]
I've built mixins for soft delete (deleted_at) and timestamps: https://github.com/iloveitaly/activemodel/tree/master/activemodel/mixins

**Comment by NotJustPizza** [comment]
There are many ways to implement this, but existing examples didn't work for me, so I'm sharing my version here for future readers:

**Timezone-unaware version (TIMESTAMP)**
```python
from datetime import datetime, timezone
from sqlmodel import Column, DateTime, Field, func

class MetadataMixin:
    # SQLAlchemy / database only field, skips Pydantic and allows value to be empty in validation
    # It also blocks you from updating it via Pydantic, but you shouldn't ever update it in the first place
    metadata_created_at = Column(DateTime, nullable=False, server_default=func.now())

    # Due to usage of SQL "upsert" statements in my codebase, "onupdate" won't work here
    # As an alternative I'm calculating value in Python and passig it via `.mode_dump()` when needed
    metadata_updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
        sa_column_kwargs={"nullable": False, "server_default": func.now()},
    )
````

**Timezone-aware version (TIMESTAMPZ)**
```python
class MetadataMixin:
    metadata_created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    metadata_updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"nullable": False, "server_default": func.now()},
    )
```

For timezone-aware version you can see more examples here: https://github.com/fastapi/sqlmodel/issues/539

For "upserts" you can use `SQLAlchemy` dialects e.g. `from sqlalchemy.dialects.postgresql import insert` and call `.on_conflict_do_update()` or try one of solutions proposed in: https://github.com/fastapi/sqlmodel/issues/59
