### ISSUE TITLE
Question: Mapping between Python and SQL types

### ISSUE THREAD

**Issue by fkromer** [tiangolo/sqlmodel#274]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
not applicable
```

### Description

I could not find documentation about how SQLModel maps Python types to SQL types. Different SQL databases do not have the same types and the types named the same may have different characteristics (e.g. length of chars in string type). These differences are abstracted away by SQLAlchemy. This means we could provide docs about type mapping from SQLModel until SQLAlchemy. What do you think about adding this to the advanced docs?

### Operating System

Other

### SQLModel Version

latest

### Python Version

latest

**Comment by oldfielj-ansto** [comment]
@fkromer For the moment mapping between Python types and SQLAlchemy types seems to be hardcoded.
I'd suspect this particular piece of code will change in the near future, so it might not be worth waiting till things are a bit more stable before doing a full writeup for the docs.

You can see the mappings in this section of the code.
https://github.com/tiangolo/sqlmodel/blob/8e97c93de0c185780c20d752ac947854e652c754/sqlmodel/main.py#L377-L416

**Comment by fkromer** [comment]
@oldfielj-ansto Thanks a lot for the reference!
