### ISSUE TITLE
No autocompletion for order by desc & gives type error if used

### ISSUE THREAD

**Issue by jd-0001** [tiangolo/sqlmodel#279]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from sqlmodel import SQLModel, create_engine, Session, select

sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

class Temp(SQLModel):
    name: str

def create_data():
    with Session(engine) as session:
        john = Temp(name="john")
        jane = Temp(name="jane")

        session.add(john)
        session.add(jane)

        session.commit()

        session.exec(select(Temp).order_by(Temp.name.desc()))
```

### Description

- Just paste this in the editor and you will get a type error. Check the screenshot.

### Operating System

Linux

### Operating System Details

Ubuntu 21.10

### SQLModel Version

0.0.6

### Python Version

3.10.2

### Additional Context

![image](https://user-images.githubusercontent.com/47495003/159851842-68ba22d3-547d-4202-8cc7-871f035cedd7.png)

No Autocompletion:
![image](https://user-images.githubusercontent.com/47495003/159851916-d0c76e09-f7b5-4f11-a510-6ada9abc2f49.png)

Related issue:
https://github.com/tiangolo/sqlmodel/issues/8

**Comment by j6e** [comment]
As per: https://sqlmodel.tiangolo.com/tutorial/where/#type-annotations-and-errors

If you wrap `Temp.name` in `col()` it won't give you a type error:

```python
from sqlmodel import SQLModel, create_engine, Session, select, col

sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

class Temp(SQLModel):
    name: str

def create_data():
    with Session(engine) as session:
        john = Temp(name="john")
        jane = Temp(name="jane")

        session.add(john)
        session.add(jane)

        session.commit()

        session.exec(select(Temp).order_by(col(Temp.name).desc()))
```

**Comment by jd-0001** [comment]
Thanks. Of I forgot that thing sorry 😉
