### ISSUE TITLE
Parent instance is not bound to a Session; lazy load operation of attribute cannot proceed

### ISSUE THREAD

**Issue by Maypher** [tiangolo/sqlmodel#309]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [x] I commit to help with one of those options 👆

### Example Code

```python
class CharacterBase(SQLModel):
    name: str
    birthdate: Optional[date]
    sex: str
    height_metric: Optional[condecimal(max_digits=5, decimal_places=2)]
    weight_metric: Optional[condecimal(max_digits=5, decimal_places=2)]


class CharacterRead(CharacterBase):
    character_id: int
    aliases: List["AliasBase"]


class Character(CharacterBase, table=True):
    character_id: Optional[int] = Field(default=None, primary_key=True)

    aliases: List["Alias"] = Relationship(back_populates="character")

    occupations: List["Occupation"] = Relationship(back_populates="character")

    creation_date: datetime = Field(default=datetime.utcnow())
    update_date: datetime = Field(default=datetime.utcnow())

class AliasBase(SQLModel):
    alias: str


class Alias(AliasBase, table=True):
    alias_id: Optional[int] = Field(default=None, primary_key=True)

    character_id: Optional[int] = Field(
        default=None, foreign_key="character.character_id"
    )

    character: Optional[Character] = Relationship(back_populates="aliases")

@router.get("/{id}", response_model=models.CharacterRead)
def get_character_by_id(id: int):
    with Session(engine) as session:
        character = session.exec(
            select(models.Character).where(models.Character.character_id == id)
        ).one()
        return character
```

### Description

The character object can have multiple aliases besides its real name and I want to return those aliases with the character data. However, when I access the route I get the error `sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Character at 0x17c52c98dc0> is not bound to a Session; lazy load operation of attribute 'aliases' cannot proceed`. Which I don't understand why. On the [tutorial](https://sqlmodel.tiangolo.com/tutorial/fastapi/relationships/) it seems to work just fine and my entire function is wrapped within a `with Session(engine) as session:`  

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.10.2

**Comment by antont** [comment]
Maybe it's because you close the session inside `get_character_by_id` as the `with` block ends. SQLModel then tries to convert it to the ResponseModel type, and accesses the db relation, but the session is already closed so it can't query anymore. The relation is lazy so it's not fetched in your db get.

I think it will work when you use the `Depends` mechanism for the session, i guess it closes it later.

The tutorial you link to does that by saying:
`session: Session = Depends(get_session)`

Other option would be to declare the relation not-lazy (joined or selectin), but maybe the lazy fetch is better for you.

**Comment by Maypher** [comment]
@antont Using `Depends` worked. The parent instance is now bound to the session but another issue came up. Now it raises a `pydantic.errors.ConfigError: field "aliases" not yet prepared so type is still a ForwardRef, you might need to call CharacterRead.update_forward_refs()`.

I called `update_forward_refs()` before returning but it still shows up

**Comment by Maypher** [comment]
Forget it, I fixed it. It turns out I just had to declare the `Alias` table before the `Character` table. Pydantic didn't like me referencing a not yet created table
