### ISSUE TITLE
Before sqlmodel I used pydantic modle as input and output Schema . But now  i m switched with the sqlmodel but i have some issue , some field(like password) that i don,t want to gave to the user in output schema how it will be restricted:  

### ISSUE THREAD

**Issue by israr96418** [tiangolo/sqlmodel#310]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class Book(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str
    description: str
```

### Description

Before sqlmodel I used pydantic modle as input and output Schema . But now  i m switched with the sqlmodel but i have some issue , some field(like password) that i don,t want to gave to the user in output schema how it will be restricted:  

### Operating System

Linux

### SQLModel Version

0.0.6

### Python Version

3.9.5

**Comment by antont** [comment]
@Maypher has it right. There's a more expanded example in the tutorial, with a base class and what would be here a UserCreate class to define the fields required in a POST call to create such an entity etc. https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/

**Comment by israr96418** [comment]
@Maypher Thank u it solve my problem

**Comment by nidico** [comment]
@israr96418 - you might want to close the issue then :)

**Comment by tiangolo** [comment]
Thanks for the help here @Maypher, @antont, and @nidico! And thanks for coming back and closing the issue @israr96418. 🍰 ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue and they piled up through time, but now I'm checking each one in order.

**Comment by Ashvith10** [comment]
How about something like:

```python
from sqlmodel import SQLModel

class UserBase(SQLModel):
    id: int
    name: str

class UserIn(UserBase, table=True):
    password: str

class UserOut(UserBase):
    pass
```

...since this also resembles the Pydantic input and output model design?
