### ISSUE TITLE
How can I differentiate fields from the endpoint layer to the field in the DB?

### ISSUE THREAD

**Issue by Miguelme** [tiangolo/sqlmodel#311]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class Task(SQLModel):
    name = Field()
    status = Field() # This one I would like it to be a string for the API and an integer for DB
```

### Description

I would like to know if I can have a different representation of a value using SQLModel. This would aim for the normal process of handling ENUMS as integer values in the DB but as Readable values in the API:

Let's say that I have a field `status` with the following possible values: (`IN_PROGRESS`, `DONE`) but in the DB, I want this field to be numeric: `0` for `IN_PROGRESS` and `1` for `DONE`, is this possible or with SQLModel I am forced to have the same representation for both API and DB Layer? 

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

3.9

**Comment by oldfielj-ansto** [comment]
@Miguelme It sounds like you need to define a response model, assuming you are using SQLModel with FastAPI.
Essentially a response model splits your model structure out so you can have "In", "Out" and "DB" models as an example.

When you define "response_model" on an endpoint you can return an instance of your database model, then FastAPI will automatically convert the instance into an instance of your response model or "Out" model.

Take a look at these docs, should be fairly straight forward, also note that your response model can simply be a Pydantic model.
https://sqlmodel.tiangolo.com/tutorial/fastapi/response-model/
https://fastapi.tiangolo.com/tutorial/response-model/
