### ISSUE TITLE
How to access underlying sqlalchemy column in order to use `regexp_match` in a `where` clause?

### ISSUE THREAD

**Issue by taranlu-houzz** [tiangolo/sqlmodel#329]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# I don't have example code because I am not sure if this is possible when using sqlmodel.

# This is the example from the `sqlalchemy` documentation for using `regexp_match`
stmt = select(table.c.some_column).where(
    table.c.some_column.regexp_match('^(b|c)')
)
```

### Description

I would like to be able to use pattern matching in a `where` clause. It appears that `sqlalchemy` supports this, but I cannot find any information on how I would be able to access this when using a model that uses `sqlmodel.SQLModel`.

This is a link to the `sqlalchemy` documentation for the functionality that seems to make the most sense to use: https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.regexp_match

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

PyPy 7.3.9 (Python 3.9.12)

**Comment by gazpachoking** [comment]
You should just be able to do it in the normal SQLAlchemy ORM way.
```python
select(SomeTable).where(SomeTable.some_column.regexp_match('^(b|c)'))
```

**Comment by taranlu-houzz** [comment]
@gazpachoking Hey, great, that works as expected! I was led astray by intellisense in VSCode not showing that as an available method. Thank you for your help.

**Comment by gazpachoking** [comment]
To get some autocomplete, you can wrap it in `sqlmodel.col`
```python
select(SomeTable).where(col(SomeTable.some_column).regexp_match('^(b|c)'))
```
