### ISSUE TITLE
[Doc] Validation for adding documentation on how to use SQLModel with AsyncSession

### ISSUE THREAD

**Issue by Cedric-Magnan** [tiangolo/sqlmodel#33]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional
from fastapi import FastAPI
from sqlmodel import Field, SQLModel, select
from sqlmodel.ext.asyncio.session import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine


sqlite_file_name = "database.db"
sqlite_url = f"sqlite+aiosqlite:///{sqlite_file_name}"
connect_args = {"check_same_thread": False}
engine = create_async_engine(sqlite_url, future=True, echo=True, connect_args=connect_args)


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None


app = FastAPI()


@app.on_event("startup")
async def startup():
    # create db tables
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.drop_all)
        await conn.run_sync(SQLModel.metadata.create_all)


@app.post("/heroes/")
async def create_hero(hero: Hero):
    async with AsyncSession(engine) as session:
        session.add(hero)
        await session.commit()
        await session.refresh(hero)
        return hero


@app.get("/heroes/")
async def read_heroes():
    async with AsyncSession(engine) as session:
        heroes = await session.exec(select(Hero))
        return heroes.all()
```

### Description

What would be the best way to use async / await with the AsyncSession ?

I've implemented a first draft here :
[fastapi-async-sqlmodel](https://github.com/Cedric-Magnan/fastapi-async-sqlmodel)

But I feel like there is a better solution than using the aiosqlite driver.

If you think this is the proper way to use async / await, I will try to add it to the documentation.

### Wanted Solution

I would like to add some documentation on how to use async / await with the SQLModel AsyncSession

### Wanted Code

```python
NA
```

### Operating System

Linux, Windows, macOS, Other

### SQLModel Version

0.0.4

### Python Version

3.7.9

**Comment by perfecto25** [comment]
thanks for that repo @Cedric-Magnan really helpful w setting up async functions

**Comment by joaopfg** [comment]
@Cedric-Magnan 

Thanks for the example ! How can I adapt it to work with postgresql ? 

I'm using a well-known docker image (postgres:13.0-alpine) to launch a container that runs a postgresql db server. 

However, I'm getting the following exception from sqlalchemy: 

`sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'psycopg2' is not async.`
