### ISSUE TITLE
How create a ModelMixin?

### ISSUE THREAD

**Issue by yurihartmann** [tiangolo/sqlmodel#330]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from datetime import datetime
from typing import Optional

from sqlalchemy.orm import declared_attr
from sqlmodel import Field, Relationship, SQLModel


class ModelMixin:
    __name__: str
    __config__ = {}

    created_at: datetime = Field(default_factory=datetime.utcnow)
    update_at: datetime = Field(default=datetime.utcnow)
    deleted_at: datetime = Field(default=None, nullable=True)


class Phone(ModelMixin, SQLModel, table=True):

    id: Optional[int] = Field(default=None, primary_key=True)
    cellphone: str
    is_active: Optional[bool] = Field(default=True)
```

### Description

- Created the ModelMixin with fields
- Created the model Phone
- extends ModelMixin in Phone
- When run code "SQLModel.metadata.create_all(self._engine)" only fields in Phone is created
- The fields created_at, update_at and deleted_at is ignorated

### Operating System

macOS

### Operating System Details

macos 12.3.1

### SQLModel Version

0.0.6

### Python Version

Python 3.9.9

**Comment by yurihartmann** [comment]
In SQLAlchemy exist = https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html

**Comment by antont** [comment]
Didn't you fix this in https://github.com/tiangolo/sqlmodel/pull/256/files ?

Anyway, like discussed there too, we also just inherit from SQLModel. Our classes don't inherit anything else though.

**Comment by yurihartmann** [comment]
Great, worked with extends SQLModel in ModelMixin class! Thanks for help!! 😁

**Comment by byrman** [comment]
> Didn't you fix this in https://github.com/tiangolo/sqlmodel/pull/256/files ?

That fix works fine for methods and simple attributes, but unfortunately not for model fields, which have to be processed by metaclass machinery. I didn't realise that until I tried this use case.
