### ISSUE TITLE
Wrong statement in documentation about SQLModel.metadata.create_all()

### ISSUE THREAD

**Issue by AlexanderFarkas** [tiangolo/sqlmodel#34]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
No code involved
```

### Description

Moving create_all to function [here](https://sqlmodel.tiangolo.com/tutorial/create-db-and-table/#refactor-data-creation) just prevents creation on first import. Python modules are executed only once, you can check it yourself. 

So statement "If SQLModel.metadata.create_all(engine) was not in a function and we tried to import something from this module (from this file) in another, it would try to create the database and table every time." is wrong ("every time" in particular).  

### Operating System

macOS

### SQLModel Version

0.0.4

### Python Version

3.9.5

**Comment by tiangolo** [comment]
Thanks for the discussion! I added https://github.com/tiangolo/sqlmodel/pull/426 to improve the text. If you feel like there's something else to be done, please let me know. If it seems clearer to you now, you can close the issue. :coffee:
