### ISSUE TITLE
Cannot get nested objects when converting to dict

### ISSUE THREAD

**Issue by farahats9** [tiangolo/sqlmodel#347]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import sqlalchemy as sa
from sqlalchemy import func
from sqlalchemy import orm
from sqlmodel import Field, Relationship, SQLModel


class Address(SQLModel, table=True):
    __tablename__ = 'addresses'

    id: Optional[int] = Field(default=None, primary_key=True, nullable=False)
    listing: 'Listing' = Relationship(back_populates='address')
    location: 'Location' = Relationship(back_populates='addresses')

class ListingImage(SQLModel, table=True):
    __tablename__ = 'listing_images'

    id: Optional[int] = Field(default=None, primary_key=True, nullable=False)
    listing: 'Listing' = Relationship(back_populates='images')
    file: str = Field(max_length=255, nullable=False)
    listing_id: int = Field(foreign_key='listings.id', nullable=False)

class Listing(SQLModel, table=True):
    __tablename__ = 'listings'

    created: Optional[datetime] = Field(sa_column_kwargs={'server_default': func.now()}, index=True)
    title: str = Field(max_length=100, nullable=False)
    price: int = Field(nullable=False)
    address_id: int = Field(foreign_key='addresses.id', nullable=True)
    id: Optional[int] = Field(default=None, primary_key=True, nullable=False)
    images: List['ListingImage'] = Relationship(back_populates='listing', sa_relationship_kwargs={'cascade': 'all, delete'})
    address: 'Address' = Relationship(back_populates='listing', sa_relationship_kwargs={'cascade': 'all, delete', 'uselist': False})

    __mapper_args__ = {"eager_defaults": True}



async def get_multi(
    self, db: AsyncSession, *, skip: int = 0, limit: int = 100, order: Any = None, **filters
) -> List[Listing]:
    stmt = sa.select(Listing).options(orm.selectinload(Listing.images), orm.selectinload(Listing.address)).filter_by(**filters).order_by(order).offset(skip).limit(limit)
    result = await db.scalars(stmt)
    return result.all()

##### in some async function ####

data = await get_multi(....)

data[0].address
shows Address(...) object normally

data[0].dict()

{
"id":..
"created":...
"title":...
"price":...
"address_id":...
}

no "images" or "address" nested object after converting to dict
```

### Description

When trying to convert an object using .dict() or .json() the resulting object does not include the nested fields like Address or Images in my example.

I am using SQLAlchemy AsyncSession and doing eager loading of the objects when quering the DB.
The nested object shows normally when trying to access it but it doesn't show up in resulting dict and json object and by contrast not being sent in FastAPI response.

I can confirm this is not the case in Pydantic and models from Pydantic work fine when converted to dict.

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.8.8

**Comment by JLHasson** [comment]
See SQLAlchemy "loading relationships": https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html

You need to set the type of loading you want to perform on the relationship. This can be passed to the `sa_relationship_kwargs` parameter. From your post it appears you want `"joined"` which would join the class you at calling `.dict()` on with the relationship class. Obviously keep in mind the performance implications of this.

```python
    sa_relationship_kwargs.update(
        {"lazy": "joined"},
    )
```

**Comment by farahats9** [comment]
@JLHasson  Thank you for your response.

However, I tried adding the additional kwarg in the sa_relationship_kwargs on the class definition but it didn't work. I tried "joined" and "selectin" both didn't return the "address" field when converted to dict. I am not sure what I am doing wrong but when using a Pydantic model instead of SQLModel it works fine. 

The model is loading the related "address" correctly before the dict conversion though. It makes me feel sure that the query statements are correct.

**Comment by Touexe** [comment]
Same to @farahats9 's problem i did passed `{"lazy": "joined"}` to `sa_relationship_kwargs` and pretty sure the attribute i wanted was fetched....by normally printing the object the attribute was shown, but not available once converting to dictionary using `.dict`.

**Comment by byrman** [comment]
What you expect cannot work, I think: Listing is referencing Address, Address is referencing Listing, etc. That would cause a maximum recursion error. This problem is described [here](https://sqlmodel.tiangolo.com/tutorial/fastapi/relationships/#dont-include-all-the-data). Instead, you could design a `ListingRead` that references an `AddressWithoutListing` and do something like `ListingRead.from_orm(data[0]).dict()`.

**Comment by farahats9** [comment]
@byrman  I tried that and it doesn't have any effect, I used the `class Config` and added `fields = {"listing":{"exclude":True }}` I really hope to find a solution for this because I don't want to port all the project to Pydantic again.

**Comment by byrman** [comment]
I don't think you will get it working for table models, you'll need models with `table=False`. I tried my own suggestion for data models and it works fine.

**Comment by farahats9** [comment]
You are right!
it worked when I inherited directly from the `ListingBase` model that has `table=False`. Its worth to note that using this way you need to do `.update_forward_refs()` or the docs won't open (and probably CRUD won't work)

**Comment by HuguesGallier** [comment]
Just reopening it to include another possible way of solving it.

I have created a base SQLModel for all my tables, with the following functions:

```
def string_lower_and_singular(string: str) -> str:
    return string.lower().removesuffix("s")


def list_of_strings_difference_plural_insensitive(list_1: List[str], list_2: List[str]) -> List[str]:
    """Keep the lower strings from list_1 if they do not appear in singular or plural form in list 2. """
    final_list, iterated_singular_strings = [], [string_lower_and_singular(string) for string in list_2]
    for string in list_1:
        if string_lower_and_singular(string) not in iterated_singular_strings:
            final_list.append(string.lower())
            iterated_singular_strings.append(string_lower_and_singular(string))
    return final_list

class BaseRelation(SQLModel):
    """Create base class for all relations."""

   [...custom code...]

    def as_dict(self, classes_iterated: list = None) -> dict:
        """Get nested fields under the convention that a class Parent will be referenced as relationship parent in a dependent class."""
        return {
            **self.dict(),
            **self._sqlmodel_relationships_as_dict(classes_iterated or [type(self).__name__.lower()])
        }

    def _sqlmodel_relationships_as_dict(self, classes_iterated: list = None) -> dict:
        dictionary = {}
        for key in list_of_strings_difference_plural_insensitive(list(self.__sqlmodel_relationships__), classes_iterated):
            classes_iterated.append(key)
            value = self.__getattribute__(key)
            if isinstance(value, Iterable):
                dictionary[key] = [inner_value.as_dict(classes_iterated) for inner_value in value]
            elif isinstance(value, BaseRelation):
                dictionary[key] = value.as_dict(classes_iterated)
        return dictionary

```

This allows me to ask for a dictionary and get the nested fields, without infinite loops. This supposes some code structure in terms of naming of relationships and field names but in a standard way.

This is also much more convenient than defining Address and AddressWithoutListing (etc...) tables.

There might be some refinement to do, but the basic idea should be working.

If this gets validated by others, I might do a PR for it :)

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue @farahats9  👍
