### ISSUE TITLE
Joining b/w two tables

### ISSUE THREAD

**Issue by israr96418** [tiangolo/sqlmodel#360]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class UserInSchema(SQLModel):
    name: str
    phone: str


class User(UserInSchema, table=True):
    __tablename__ = "user_data"
    id: Optional[int] = Field(default=None, primary_key=True)
    cars: List["Car"] = Relationship(back_populates="user")




class CarInSchema(SQLModel):
    name: str
    color: str


class Car(CarInSchema, table=True):
    __tablename__ = "car_data"
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(default=None, foreign_key="user_data.id")
    user: Optional[User] = Relationship(back_populates="cars")
```

### Description

I have two model one is user and other one is car .. i want to make the relationship b/w these two model as one user can buy many cars .

@router.get("/")
def get():
    statement = select(Car, User).join(User)
    result = session.exec(statement)
    return result

but it give the error:
TypeError: User() missing 1 required positional argument: 'data'

### Operating System

Linux

### SQLModel Version

0.0.6

### Python Version

3.9.13

**Comment by phi-friday** [comment]
you should use `select(Car, User).select_from(join(Car, User))` instead of `select(Car, User).join(User)`

```python
from sqlmodel import SQLModel, Field, Relationship, create_engine, select, Session, join
from typing import Optional, List

engine = create_engine("sqlite://")


class UserInSchema(SQLModel):
    name: str
    phone: str


class User(UserInSchema, table=True):
    __tablename__ = "user_data"  # type: ignore
    id: Optional[int] = Field(default=None, primary_key=True)
    cars: List["Car"] = Relationship(back_populates="user")


class CarInSchema(SQLModel):
    name: str
    color: str


class Car(CarInSchema, table=True):
    __tablename__ = "car_data"  # type: ignore
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(default=None, foreign_key="user_data.id")
    user: Optional[User] = Relationship(back_populates="cars")


stmt = select(Car, User).select_from(join(Car, User))

with Session(engine) as session:
    SQLModel.metadata.create_all(session.bind)

    user = User(name="user", phone="phone")
    car = Car(name="car", color="color")
    car.user = user
    session.add(user)
    session.add(car)
    session.commit()

    data = session.exec(stmt).all()

print(data)
# data=[(Car(name='car', user_id=1, id=1, color='color'), User(phone='phone', name='user', id=1))]
```

**Comment by israr96418** [comment]
Thanks, it resolved my problem
