### ISSUE TITLE
How to create a time Field for a model like django DateTimeField

### ISSUE THREAD

**Issue by regainOWO** [tiangolo/sqlmodel#370]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from datetime import datetime
from typing import Optional
from sqlmodel import Field, SQLModel, DateTime


class Image_Save_Record(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

    camera_ip: str
    camera_channel: int
    file_path: str
    file_name: str
    create_time: DateTime 
    update_time: DateTime
```

### Description

when i create a Image_Save_Record instance and commit it to db, the create_time field value should be that system time current.
``` python
# django version
create_time = models.DateTimeField(auto_now_add=True)
```
when i change the Image_Save_Record instance which i created before and commit it to db, the update_time field value should be that system time current.
``` python
# django version
update_time = models.DateTimeField(auto_now=True)
```
Is there sqlmodel have option to do the same like this?

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.7.9

**Comment by RobertRosca** [comment]
Here is my very rough example code:

```python3
import time
from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, Session, SQLModel, create_engine, select


class Model(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

    foo: Optional[str]

    created_at: Optional[datetime] = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now())
    )

    updated_at: Optional[datetime] = Field(
        sa_column=Column(DateTime(timezone=True), onupdate=func.now())
    )


sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def create_entry():
    with Session(engine) as session:
        m = Model()

        print(f"created {m=}")

        session.add(m)
        session.commit()
        session.refresh(m)

        print(f"added and refreshed {m=}")


def update_entry():
    with Session(engine) as session:
        s = select(Model)
        m = session.exec(s).first()

        print(f"\nfound {m=}")

        m.foo = "bar"

        print(f"modified {m=}")

        session.add(m)
        session.commit()
        session.refresh(m)

        print(f"refreshed {m=}")


def main():
    create_db_and_tables()
    create_entry()
    time.sleep(5)
    update_entry()


if __name__ == "__main__":
    main()
```

Running it outputs:

```
created m=Model(id=None, foo=None, created_at=None, updated_at=None)
added and refreshed m=Model(foo=None, created_at=datetime.datetime(2022, 6, 29, 8, 14, 53), updated_at=None, id=1)

found m=Model(foo=None, created_at=datetime.datetime(2022, 6, 29, 8, 14, 53), updated_at=None, id=1)
modified m=Model(foo='bar', created_at=datetime.datetime(2022, 6, 29, 8, 14, 53), updated_at=None, id=1)
refreshed m=Model(foo='bar', created_at=datetime.datetime(2022, 6, 29, 8, 14, 53), updated_at=datetime.datetime(2022, 6, 29, 8, 14, 58), id=1)
```

So `created_at` is constant, and `update_at` is 5 seconds after `created_at` as expected given the 5 second sleep between creation and update.

**Comment by regainOWO** [comment]
@RobertRosca This example is very detailed! thanks a lot!

**Comment by RobertRosca** [comment]
Thanks! Happy it helped :smile: 

I wrote up an explanation and created PR https://github.com/tiangolo/sqlmodel/pull/372 to add this to the documentation, since it does come up pretty often.

**Comment by RobertRosca** [comment]
I know #372 isn't merged yet, but if my example helped answer your question could you close this issue? Thanks :smile: 

Feel free to leave comments or suggestions on #372 as well if you have any!

**Comment by Proahmedjaved** [comment]
@RobertRosca This is really helpful but there is an issue with `created_at` field. datetime on created_at is fixed for every resource creation. `server_default ` assigns default data directly to the table when using alembic.

**Comment by RobertRosca** [comment]
So when using the example code I showed with Alembic instead of `SQLModel.metadata.create_all` the `created_at` field always has the same value, as if the default value were set to a constant datetime?

I haven't tested it with Alembic, but [their docs](https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.add_column) show that the `server_default=func.now()` should work to set the time to the current time for a timestamp column:

```python3
from alembic import op
from sqlalchemy import Column, TIMESTAMP, func

# specify "DEFAULT NOW" along with the column add
op.add_column('account',
    Column('timestamp', TIMESTAMP, server_default=func.now())
)
```

I guess there could be some issue with interactions between Alembic, SQLAlchemy, and SQLModel causing the default to be a constant instead of the now function, but I haven't had time to look.

Since this should be supported by Alembic then if this isn't working correctly it's probably an issue in SQLModel, so I'd say open an issue here with some example code. I'll try and have a look some time this week as well, but maybe somebody else would be able to help before I can :smile:

**Comment by tiangolo** [comment]
Thanks a lot for the help here @RobertRosca ! 🍰

And thanks @regainOWO for coming back to close the issue. ☕

**Comment by FilipeMarch** [comment]
I don't understand... this definitely does not work for me.
I have a database containing some users, when I add the column `created_at` and execute `alembic upgrade head`  I get this error:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a column with non-constant default
[SQL: ALTER TABLE users ADD COLUMN created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)]
```

migration script:
```python
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
```

I just added this line to `Users` table:
```python
    created_at: Optional[datetime.datetime] = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now())
    )
```

**Comment by FilipeMarch** [comment]
I figured out this works:
I added these lines to `User` table:
```python
    created_at: datetime.datetime = Field(
        default_factory=datetime.datetime.utcnow,
        nullable=False,
    )
```

In `env.py`  I added the argument `render_as_batch=True` to `context.configure`.
I autogenerated the migration.
I changed the `upgrade` function to add the `created_at` column with **nullable=True**, I updated the values with `sa.func.now` and then I `batch_alter_table` to make it nullable=True.

```python
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Adding column created_at")
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    # Get the users.created_at column
    user = sa.sql.table(
        "users",
        sa.sql.column("created_at", sa.DateTime()),
    )
    # Update the users.created_at column
    op.execute(user.update().values(created_at=sa.func.now()))

    with op.batch_alter_table("users", schema=None) as batch_op:
        # Set the users.created_at column to not null
        batch_op.alter_column("created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")
```

**Comment by FilipeMarch** [comment]
I also implemented `updated_at` field here with the following:
Add this to the your `SQLModel`:
```python
updated_at: Optional[datetime.datetime] = Field(
        sa_column=Column(DateTime(), onupdate=func.now())
    )
```

Alembic migration:
```python
def upgrade() -> None:
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))

def downgrade() -> None:
    op.drop_column("users", "updated_at")

```

Or in case you are using batch operation:
```python
def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

def downgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
```

**Comment by jwezel** [comment]
This doesn't work if I factor out a field with `sa_column` attribute to another class and inherit from it, like:

```python
class WithId(SQLModel):
    """
    Database row with ID field
    """

    id: UUID = Field(default_factory=lambda: ULID().to_uuid(), description='Row ULID', primary_key=True)


class TimedRow(SQLModel):
    """
    Database row with status times
    """

    created: datetime = Field(
        default_factory=lambda: datetime.now(tz=config.timezone),
        sa_column=Column(DateTime(timezone=True), server_default=text('CURRENT_TIMESTAMP'), nullable=False),
        description='Time when row was created',
    )
    updated: datetime | None = Field(
        sa_column=Column(DateTime(timezone=True)),
        description='Time when row was last updated',
    )
    deleted: datetime | None = Field(
        sa_column=Column(DateTime(timezone=True)),
        description='Time when row was deleted',
    )

class Practice(TimedRow, WithId, table=True):

    name: str

```

If I have definitions like `Practice` _in more than one module_, I get:

```
sqlalchemy.exc.ArgumentError: Column object 'created' already assigned to Table '<tablename>'
```

on the second and following import of such a module.
