### ISSUE TITLE
previously working model code breaks after fresh environment setup

### ISSUE THREAD

**Issue by clstaudt** [tiangolo/sqlmodel#386]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python



def OneToOneRelationship(back_populates):
    return Relationship(
        back_populates=back_populates,
        sa_relationship_kwargs={"uselist": False},
    )

class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    subtitle: str
    website: str
    email: EmailStr
    phone_number: str
    address_id: Optional[int] = Field(default=None, foreign_key="address.id")
    address: Optional[Address] = Relationship(back_populates="users")
    VAT_number: Optional[str]
    # User 1:1* ICloudAccount
    icloud_account_id: Optional[int] = Field(
        default=None, foreign_key="icloudaccount.id"
    )
    icloud_account: Optional["ICloudAccount"] = Relationship(back_populates="user")
    bank_account_id: Optional[int] = Field(default=None, foreign_key="bankaccount.id")
    bank_account: Optional["BankAccount"] = Relationship(back_populates="user")
    logo: Optional[str]


class ICloudAccount(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_name: str
    user: User = OneToOneRelationship(back_populates="icloud_account")


def test_user():
    user = model.User(
        name="Archibald Tuttle",
        subtitle="Heating Engineer",
        email="harry@tuttle.com",
    )

    icloud_account = model.ICloudAccount(
        user_name=user.email,
    )

    user.icloud_account = icloud_account

    assert icloud_account.user.name == "Archibald Tuttle"
```

### Description

The above unit test fails with

```
>       assert icloud_account.user.name == "Archibald Tuttle"
E       AttributeError: 'ICloudAccount' object has no attribute 'user'
```

What is weird about this is that this is well-tested code that was running before. I set up a new Python environment, but using the same latest version  0.0.6 of sqlmodel. How can I investigate the problem?

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

Python 3.9.13

**Comment by Apollo314** [comment]
#315 again.

**Comment by clstaudt** [comment]
@Apollo314  Thanks, this fixed the test failures. Hoping for a new release of sqlmodel soon that removes the need to pin sqlalchemy.
