### ISSUE TITLE
Support for typing._GenericAlias when creating table

### ISSUE THREAD

**Issue by mattyoungberg** [tiangolo/sqlmodel#387]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# Python 3.7.9
from pydantic import BaseModel
from sqlmodel import SQLModel
from typing_extensions import Literal


class PydanticClass(BaseModel):
        colors: Literal['red', 'blue', 'green'] = 'red'


class SQLModelClass(SQLModel, table=True):
        colors: Literal['red', 'blue', 'green'] = 'red'
```

### Description

Due to a dependency, I'm constrained to Python 3.7.9, but I'm wanting to take advantage of the `Literal` type. I'm backporting it via the `typing_extensions` library.

When creating a table SQLModel that contains a field typed as the backported LIteral, I get the following traceback (taken from the provided example code):

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    class SQLModelClass(SQLModel, table=True):
  File "C:\...\venv\lib\site-packages\sqlmodel\main.py", line 298, in __new__
    col = get_column_from_field(v)
  File "C:\...\venv\lib\site-packages\sqlmodel\main.py", line 424, in get_column_from_field
    sa_type = get_sqlachemy_type(field)
  File "C:\...\venv\lib\site-packages\sqlmodel\main.py", line 379, in get_sqlachemy_type
    if issubclass(field.type_, str):
TypeError: issubclass() arg 1 must be a class
```

When debugging, I'm finding that the `colors` field's attribute `type_` is an instance of `typing._GenericAlias.`. When I look at the `typing` library, it looks to be a normal class, so I'm not sure why the interpreter would say it's not a class.

The workaround for my project I'm going to implement is simply adding validators to the class, but I wanted to cover my bases and make sure this was reported, both for the project's sake and in case anyone else has an answer.

### Operating System

Windows

### Operating System Details

I'm developing on WIndows using Docker with a Debian base image. I get the same error regardless of whether I run it locally or in a container.

### SQLModel Version

0.0.6

### Python Version

3.7.9

**Comment by meirdev** [comment]
Literal can contain many types, e.g:

```python
from typing_extensions import Literal

def foo(arg: Literal[1, "Hello", False, b"World"]):
    pass
```

So you need to specify the column type to save it in the database:

```python
from typing_extensions import Literal
from sqlalchemy import Column, String

class SQLModelClass(SQLModel, table=True):
    colors: Literal['red', 'blue', 'green'] = Field(default='red', sa_column=Column(String))
```

**Comment by mattyoungberg** [comment]
This fixed it! Thank you, @meirdev.
