### ISSUE TITLE
How to ORDER BY specific order

### ISSUE THREAD

**Issue by dilless** [tiangolo/sqlmodel#388]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```sql
SELECT
	id,
	`name` 
FROM
	tb_shop 
WHERE
	id IN ( 1, 2, 3 ) 
ORDER BY
	FIELD( id, 2, 1, 3 )
```

### Description

How to use sqlmodel to implement the above sql query with specific order？

### Operating System

Windows

### SQLModel Version

0.0.6

### Python Version

3.7.6

**Comment by meirdev** [comment]
You can use any function from sqlalchemy:

```python
import sqlalchemy
from sqlmodel import select

select(
    Hero.id,
    Hero.name,
).where(
    Hero.id.in_([1, 2, 3]),
).order_by(
    sqlalchemy.func.field(Hero.id, 2, 1, 3),
)
```
