### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [tiangolo/sqlmodel#418]
Hello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/sqlmodel-feedstock

**Comment by tiangolo** [comment]
Thanks! Yes, absolutely, although I can't ensure I'll be able to commit a lot to it, but I would like to be part of that. What should I do?

**Comment by thewchan** [comment]
@tiangolo Very little work is needed from maintainers since new updates are generated by bots as updates are pushed to PyPI upstream. Maintainers are notified and they can merge them, esp when all tests pass. If tests don't pass it usually we (maintainers) need to go in and update the yaml recipe, it's quite self explanatory but I can take the lead on that.

**Comment by tiangolo** [comment]
Great, thanks! :rocket:
