### ISSUE TITLE
JSON and Array types for sqlmodel

### ISSUE THREAD

**Issue by mv-yurchenko** [tiangolo/sqlmodel#42]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, SQLModel, JSON, ARRAY


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: JSON
    age: Optional[int] = None
```

### Description

Got following error: 
`   new_cls = super().__new__(cls, name, bases, dict_used, **config_kwargs)
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 456, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 670, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 715, in find_validators
RuntimeError: no validator found for <class 'sqlalchemy.sql.sqltypes.JSON'>, see `arbitrary_types_allowed` in Config`

### Operating System

macOS

### SQLModel Version

0.0.4

### Python Version

3.8.0

**Comment by FalseDev** [comment]
`ARRAY` needs a generic type argument like so

```py
array: ARRAY[float]
```

Try updating your code to:
```py
from sqlmodel import (
    Field, ARRAY, SQLModel, create_engine
)


class ArrayData(SQLModel, table=True):
    """Array ORM model"""
    
    uuid: str = Field(primary_key=True)
    array: ARRAY[float] = [1.0]
        
    class Config:
        arbitrary_types_allowed = True
```

**Comment by mv-yurchenko** [comment]
@FalseDev 
Tried it. Got following error:
`sqlalchemy.exc.CompileError: (in table 'arraydata', column 'array'): Can't generate DDL for NullType(); did you forget to specify a type on this Column?
`

**Comment by Chunkford** [comment]
@mv-yurchenko see if this works?

```
from typing import List
from sqlmodel import Field, ARRAY, SQLModel, create_engine, Float


class ArrayData(SQLModel, table=True):
    uuid: str = Field(primary_key=True)
    array: List[float] = Field(sa_column=Column(ARRAY(Float)))
```

**Comment by yngtdd** [comment]
Thanks @Chunkford, that works!

**Comment by mv-yurchenko** [comment]
Thanks a lot for all!!!

**Comment by raphapassini** [comment]
Hey guys, I guess this is a good topic for the documentation, @tiangolo what do you think? I can send a PR with some docs if you want to :)

**Comment by mv-yurchenko** [comment]
@raphapassini Absolutely need it

**Comment by Chunkford** [comment]
There defiantly needs to be info on [sa_column](https://github.com/tiangolo/sqlmodel/blob/02da85c9ec39b0ebb7ff91de3045e0aea28dc998/sqlmodel/main.py#L155), plus [sa_column_args](https://github.com/tiangolo/sqlmodel/blob/02da85c9ec39b0ebb7ff91de3045e0aea28dc998/sqlmodel/main.py#L156), [sa_column_kwargs](https://github.com/tiangolo/sqlmodel/blob/02da85c9ec39b0ebb7ff91de3045e0aea28dc998/sqlmodel/main.py#L157) and [schema_extra](https://github.com/tiangolo/sqlmodel/blob/02da85c9ec39b0ebb7ff91de3045e0aea28dc998/sqlmodel/main.py#L158) as I have no idea what use cases these are for. But then I have jumped in the deep end with hardly any knowledge of SQLAlchemy, FastAPI and Pydantic :)

**Comment by mv-yurchenko** [comment]
And I think examples with JSON and Array types will be very useful

**Comment by cworkschris** [comment]
> And I think examples with JSON and Array types will be very useful

Exactly - I'm confused how the Array solution of specific typing translates to JSON (the more experimentation I do the more confused I get 🙃️  pydantic newb here)

**Comment by Spenhouet** [comment]
> = Field(sa_column=Column(ARRAY(Float)))

I tried this but I can not get it to work:

> CompileError: (in table 'block', column 'transactions'): Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x7f09aae2f690> can't render element of type ARRAY

I have the following field:

```python
transactions: List[HexStr] = Field(sa_column=Column(ARRAY(String)))
```

Where HexStr is just a custom pydantic type:

```python
class HexStr(str):

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v: Union[str, HexBytes]):
        if isinstance(v, HexBytes):
            return Web3.toHex(v)
        elif isinstance(v, str):
            return v
        else:
            raise NotImplementedError(f"Type {type(v)} unknown.")
```

I want a simple list of strings in the database cell. I can not find anything on that in the SQLModel documentation.

@Chunkford, @tiangolo any idea?

**Comment by Chunkford** [comment]
@Spenhouet I think you might find it's because SQLite doesn't support the ARRAY data type.

**Comment by mbanerjeepalmer** [comment]
Since this is one of relatively few search results for how to use JSON, I should mention that got it to work by importing `JSON` from `sqlmodel` and passing that in: `event: str = Field(sa_type=JSON)`.

Not sure if this is correct, though. (Note that my JSON is plain text, not `jsonb`.)

**Comment by rahulghara-nz** [comment]
Here is how you can do for adding Array type column

`from sqlmodel import SQLModel, Field, Column
from sqlalchemy.types import JSON, ARRAY, String
from typing import List, Optional , Set
import datetime

class Blog(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str
    content: str
    author: str
    category: str = "General"
    status: str = "Draft"  # Draft, Published, Archived
    tags: List[str] = Field(sa_column=Column(ARRAY(String))) # Fixed the issue
    featured_image_url: Optional[str] = None
    created_at: datetime.datetime = Field(default_factory=datetime.datetime.now)
    updated_at: Optional[datetime.datetime] = None`
