### ISSUE TITLE
Conditional where statements support

### ISSUE THREAD

**Issue by deajan** [tiangolo/sqlmodel#454]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, Session, SQLModel, create_engine, select, col


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None
    force: int


sqlite_url = f"sqlite:///:memory:"

engine = create_engine(sqlite_url, echo=True)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def create_heroes():
    hero_1 = Hero(name="Deadpond", secret_name="Dive Wilson", age=80, force=40)
    hero_2 = Hero(name="Spider-Boy", secret_name="Pedro Parqueador", age=21, force=30)
    hero_3 = Hero(name="Rusty-Man", secret_name="Tommy Sharp", age=48, force=50)

    with Session(engine) as session:
        session.add(hero_1)
        session.add(hero_2)
        session.add(hero_3)
        session.commit()


def find_heroes(min_age: int = None, min_force: int = None):
	with Session(engine) as session:
		statement = select(Hero)
		if min_age:
			statement = statement.where(col(Hero.age) >= min_age)
		if min_force:
			statement = statement.where(col(Hero.force) >= min_force)
		return session.exec(statement).all()


def main():
    create_db_and_tables()
    create_heroes()
    print(find_heroes(min_age=30, min_force=40))


if __name__ == "__main__":
    main()
```

### Description

When filtering using WHERE clauses, there are big chances that the filter condition might me None (example when filtering on timestamps interval and no timestamps were given).

In order to achieve conditional filtering, as for now, we need to add `.where(column >= filter_value)` statements to the current statement using `if filter_value`.

### Wanted Solution

It would be a nice shortcut to have `where_if()` directive that directly evaluates the condition and adds the WHERE clause when condition is True, see the comment in `find_heroes()` example code.

Maybe there's already a good way of doing this, or a better way than what I suggest.
I just find it ugly to write multiple `if condition` statements to add conditional filters, especially when using alot of WHERE clauses.

### Wanted Code

```python
from typing import Optional

from sqlmodel import Field, Session, SQLModel, create_engine, select, col


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None
    force: int


sqlite_url = f"sqlite:///:memory:"

engine = create_engine(sqlite_url, echo=True)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


def create_heroes():
    hero_1 = Hero(name="Deadpond", secret_name="Dive Wilson", age=80, force=40)
    hero_2 = Hero(name="Spider-Boy", secret_name="Pedro Parqueador", age=21, force=30)
    hero_3 = Hero(name="Rusty-Man", secret_name="Tommy Sharp", age=48, force=50)

    with Session(engine) as session:
        session.add(hero_1)
        session.add(hero_2)
        session.add(hero_3)
        session.commit()


def find_heroes(min_age: int = None, min_force: int = None):
	with Session(engine) as session:
		statement = select(Hero).if_where(min_age, col(Hero.age) >= min_age).where_if(min_force, col(Hero.force) >= min_force)
		return session.exec(statement).all()


def main():
    create_db_and_tables()
    create_heroes()
    print(find_heroes(min_age=30, min_force=40))


if __name__ == "__main__":
    main()
```

### Alternatives

I've searched SQLAlchemy for already existing solutions.
The following link shows that the same problem exists in SQLAlchemy (maybe ?).
https://devsheet.com/code-snippet/apply-condition-based-multiple-filters-in-sqlalchemy-query/

### Operating System

Windows

### SQLModel Version

0.0.8

### Python Version

Python 3.10.7 x64

**Comment by phi-friday** [comment]
I agree that there should be a method such as ```if_where```, but it does not seem to be a method to be added in ```sqlmodel```. 

This is because ```select``` function of ```sqlmodel``` is a form in which only type hint of ```Select``` class of ```sqlalchemy``` is added.

It may be because I simply think of ```sqlmodel``` as a thin layer between ```sqlalchemy``` and ```pydantic```.

**Comment by deajan** [comment]
Indeed, having looked at the location of `where` implementation, it's in SQLAlchemy and not SQLModel.
Sorry for the noise.

**Comment by tiangolo** [comment]
Thanks for the help here @phi-friday  ! 👏  🙇 

Thanks for reporting back and closing the issue @deajan  👍
