### ISSUE TITLE
Hide field from schema and response OR define table model without primary key

### ISSUE THREAD

**Issue by dhavalsavalia** [tiangolo/sqlmodel#455]
### First Check

- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the SQLModel documentation, with the integrated search.
- [x] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [x] I already read and followed all the tutorial in the docs and didn't find an answer.
- [x] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [x] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [x] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI
from sqlmodel import Field, SQLModel

app = FastAPI()


# User Model
class User(SQLModel, table=True):
    __tablename__ = "USER"

    rowid: str = Field(default=None, primary_key=True)
    name: str
    email: str
    password: str

# return a user
@app.get("/", response_model=User, response_model_exclude={"rowid"})
def read_root():
    # Create a user object
    user = User(name="John Doe", email="jon@doe.com", password="secret")
    return user
```

### Description

I am using a legacy Oracle database where tables don't have any primary-key on them. Initially, I tried to write table models without the primary key defined but neither SQLAlchemy nor SQLModel will let me define such tables. However, I figured out that every table has a `rowid` column which is unique to each row and I resorted to use that a primary key.

Now, the issue is that the old schema did not have this field and I am not supposed to have that in response JSON either. I also tried overriding dict() method of SQLModel class where if I pass `hidden=True` in `schema_extra` of `Field` and eventually `FieldInfo` of Pydantic and pass `exclude` for that field, but it did not work as expected and returned `rowid=null` instead. ([Ref](https://github.com/tiangolo/fastapi/issues/1378#issuecomment-727570124)). I am currently overcoming this issue with having a separate model for response, but I believe that introduces redundancies and defeats the purpose of using SQLModel.

My question is can I hide `rowid` from both schema and response OR can I define models without primary key?

#### Update

There seems to an argument `response_model_exclude` which helps excluding `rowid` from the response JSON but it is still showing up in OpenAPI spec.

### Operating System

macOS

### Operating System Details

I am using MacOS 12.4 on Apple M1 Pro Silicon. I am using Pipenv to handle the virtualenv.

### SQLModel Version

0.0.4

### Python Version

Python 3.9.14

**Comment by tiangolo** [comment]
Check out the docs for multiple models with FastAPI: https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/
