### ISSUE TITLE
SQLModel Field example param not working like Pydantic Field example param

### ISSUE THREAD

**Issue by 305jthompson** [tiangolo/sqlmodel#456]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Example #1 (This does not work)

from uuid import uuid4, UUID
from sqlmodel import SQLModel, Field as SQLModelField

class Address(AddressBase, table=True):
    id: UUID = SQLModelField(default_factory=uuid4, primary_key=True, index=True, nullable=False)
    zip: str = SQLModelField(example="12345")


Example #2 (This works)

from uuid import uuid4, UUID
from sqlmodel import SQLModel, Field as SQLModelField
from pydantic import Field as PydanticField

class Address(AddressBase, table=True):
    id: UUID = 
from sqlmodel import SQLModel, Field as SQLModelField(default_factory=uuid4, primary_key=True, index=True, nullable=False)
    zip: str = PydanticField(example="12345")
```

### Description

I am trying to set an example on the model variable 'zip' so that it shows up as '12345' in the example values section on a route in the docs page.

This is what it looks like without adding the example
```json
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "zip": "string"
}
```

This is what it looks like using the Pydantic Field value
```json
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "zip": "12345"
}
```
When using SQLModel's 'Field' the example param returns the following error:
```
TypeError: Field() got an unexpected keyword argument 'example'
```

I'm not sure if this is the intended functionality for SQLModel's 'Field' or if this should work.

What is the preferred way of setting the schema_example variable with SQLModel?

### Operating System

Linux

### SQLModel Version

0.0.8

### Python Version

Python 3.10.6

**Comment by Kazun3500** [comment]
You can use schema_extra parameter for Field

**Comment by tiangolo** [comment]
Thanks for the help here @Kazun3500  ! 👏  🙇 

If that solves the original problem, then you can close this issue @305jthompson  ✔️

**Comment by Thompson-Jordon** [comment]
Yes this works. Thanks for the help!

**Comment by chrisawad** [comment]
I don't think this works anymore unless I'm using it incorrectly:

`some_field: str = Field(schema_extra={'example': 'test'})`

The OpenAPI docs still shows "string" in the example.

**Comment by mcfoi** [comment]
@chrisawad your suggestion is almost right! 'example' => 'example**s**'  

So the working sintax is:  

```
from sqlmodel import Field  

some_field: str = Field(schema_extra={'examples': ['apple']})
```  
Note the required SQUARE BRAKETS!
