### ISSUE TITLE
How to create a required (non-optional) relationship attribute?

### ISSUE THREAD

**Issue by cdwilson** [tiangolo/sqlmodel#459]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import List, Optional

from sqlmodel import Field, Relationship, Session, SQLModel, create_engine


class Team(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    headquarters: str

    heroes: List["Hero"] = Relationship(back_populates="team")


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)
    secret_name: str
    age: Optional[int] = Field(default=None, index=True)

    team_id: int = Field(default=None, foreign_key="team.id")
    team: Team = Relationship(back_populates="heroes")


sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)


def create_db_and_tables():
    SQLModel.metadata.drop_all(engine)
    SQLModel.metadata.create_all(engine)


def create_heroes():
    with Session(engine) as session:
        team_preventers = Team(name="Preventers", headquarters="Sharp Tower")

        hero_rusty_man = Hero(
            name="Rusty-Man", secret_name="Tommy Sharp", age=48, team=team_preventers
        )
        hero_spider_boy = Hero(name="Spider-Boy", secret_name="Pedro Parqueador")
        session.add(hero_rusty_man)
        session.add(hero_spider_boy)
        session.commit()

        session.refresh(hero_rusty_man)
        session.refresh(hero_spider_boy)

        print("Created hero:", hero_rusty_man)
        print("Created hero:", hero_spider_boy)


def main():
    create_db_and_tables()
    create_heroes()


if __name__ == "__main__":
    main()
```

### Description

The [SQLModel docs](https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/define-relationships-attributes/#optional-relationship-attributes) mention:

> If it was required for a `Hero` instance to belong to a `Team`, then the `team_id` would be `int` instead of `Optional[int]`.
> 
> And the `team` attribute would be a `Team` instead of `Optional[Team]`.

When I tried making this change on the tutorial code in the example above, `hero_spider_boy` is created with `team_id=None`, even though the intention was for it to be required for a `Hero` instance to belong to a `Team`.

Is there a recommended way to create a required relationship (non-optional) that would enforce the requirement that a `Hero` instance to belongs to a `Team` in this example?

### Operating System

macOS

### Operating System Details

Version: 12.6 (21G115)

### SQLModel Version

0.0.8

### Python Version

Python 3.10.6

### Additional Context

I tried removing the `default=None` attribute from `team_id: int = Field(default=None, foreign_key="team.id")`, but when I do that, I get a Pylance error saying `Argument missing for parameter "team_id"`:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/14631/194324520-a8ca30a9-fc00-46c0-aa6f-621f4f505314.png">

**Comment by cdwilson** [comment]
I found a way to achieve this by setting `nullable=False` on the `team_id` field:

```python
team_id: int = Field(default=None, foreign_key="team.id", nullable=False)
```

which results in an error like the following:

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: hero.team_id
```

I'm brand new to SQLModel (and ORM/databases in general), so if this isn't the correct way to achieve this, please feel free to add a follow up comment.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

**Comment by Ark-kun** [comment]
@cdwilson It looks like you were unable to solve the problem. Could you re-open this issue then?

**Comment by cdwilson** [comment]
@Ark-kun it's been a long time since I looked at this, but from [my comment above](https://github.com/fastapi/sqlmodel/issues/459#issuecomment-1270732936), I believe adding `nullable=False` resulted in the constraint being enforced (i.e. in the example above, the expected error is generated when trying to add `hero_spider_boy` without a `team`).

Is there something about this that is not working for you?
