### ISSUE TITLE
Alembic migration generated always set enum nullable to true

### ISSUE THREAD

**Issue by yixiongngvsys** [tiangolo/sqlmodel#466]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import enum
from sqlmodel import SQLModel, Field, UniqueConstraint, Column, Enum

class Contract_Status(str, enum.Enum):
    CREATED = "Created"
    COMPLETED = "Completed"
    DEPOSITED = "Deposited"
    CANCELLED = "Cancelled"

class Contract(SQLModel, table = True):
    __table_args__ = (UniqueConstraint("ctrt_id"),)
    ctrt_id: str = Field(primary_key = True, nullable = False)
    status: Contract_Status = Field(sa_column = Column(Enum(Contract_Status, values_callable = lambda enum: [e.value for e in enum])), nullable = False)
```

### Description

1. Create Contract Model
2. Create migration using alembic
`alembic revision --autogenerate -m "MIGRATION MESSAGE"`
3. Migration generated, however, nullable for enum is always set to True

Note: I have tested using sqlalchemy defination, and it is working but not for SQLModel. 
```
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('status', sa.Enum('Created', 'Completed', 'Deposited', 'Cancelled', name='contract_status'), nullable=True),
    sa.Column('ctrt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('ctrt_id'),
    sa.UniqueConstraint('ctrt_id')
    )
    # ### end Alembic commands ###

```

### Operating System

macOS

### SQLModel Version

0.0.8

### Python Version

3.10.5

**Comment by bvsn** [comment]
You can reuse [ChoiceType](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.choice) and set `server_default` in your migration file:
```
sa.Column("my_field", ChoiceType(MyFieldEnum), nullable=False, server_default=str(MyFieldEnum.MY_X.value))
```

Or, just to rewrite a single `ChoiceType` realization.

**Comment by yixiongngvsys** [comment]
Thanks for your reply @bvsn however my plan is to make it working from model.py files and try to reduce customisation in migration files.

**Comment by tiangolo** [comment]
Thanks for the report! This is because `nullable` is not compatible with `sa_column`, in that case you have to pass `nullable` to it.

I just added https://github.com/tiangolo/sqlmodel/pull/681 to make sure that that combination of parameters is not allowed. When `sa_column` is provided, that takes precedence. Now it will show an error when that happens, the error will happen at runtime, and there's also the type tricks so that your editor will also complain if the combination of parameters is invalid.

Also, there was recently a fix for enums, so you should be able to use the enum directly, without a `Column`. 🎉
