### ISSUE TITLE
Switching postgres schema from client side for SaaS projects

### ISSUE THREAD

**Issue by dhnchandan** [tiangolo/sqlmodel#47]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Pass
```

### Description

For SaaS we need solution to use different postgre sql schema. Different users have different tenant and have to switch schema on fly.

### Wanted Solution

Is there any solution to switch schema based on passed information from client side? Such as we can send schema name through jwt.

### Wanted Code

```python
Pass
```

### Operating System

Linux

### SQLModel Version

0.0.4

### Python Version

3.9

**Comment by Chunkford** [comment]
When you create a model you can define the schema using `__table_args__ = {'schema': 'name_of_schema_here'}`
I'm guessing you could probably use a variable instead e.g. `__table_args__ = {'schema': f'{schema_name}'}` to dynamically
change the name of the schema on the fly.

**Comment by torugok** [comment]
I found a solution for this, using sqlalchemy schema translation [sqlalchemy schema translation](https://docs.sqlalchemy.org/en/14/changelog/migration_11.html#multi-tenancy-schema-translation-for-table-objects), an example:

```py
class MultiTenantTenantTable(SQLModel):
    __table_args__ = {"schema": "tenant_schema"}

class MyTable(MultiTenantTenantTable, table=True):
    id: int = Field(primary_key=True)

# execution
tenant_schema = "MyTenantSchema"
session.connection(execution_options={"schema_translate_map": {"tenant_schema": tenant_schema}})
session.execute(select(MyTable))
```
