### ISSUE TITLE
How to join tables across multiple schemas

### ISSUE THREAD

**Issue by christianholland** [tiangolo/sqlmodel#475]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Not applicable
```

### Description

Hi there, it is possible to join tables that are '*within*' the same database but '*in different'* schemas?

Lets say I have two schemas: `A` and `B`

For schema `A` I have full control and populate it with tables with SQLModel; e.g.

```
class Sample(SQLModel, table=True):
    __table_args__ = {"schema": "A"}

    id: Optional[int] = Field(default=None, primary_key=True)
    key: int
```

For schema `B` I only have read rights. The table of interest named `Order` within schema `B` looks like this:

```
Order
id   | key |
=============
1    | 435
...  | ....
```

Now I would like to join my `Sample` table within schema `A` with the `Order` table within schema `B`. 

From my understanding I should implement the `Order` table as pydantic model which I can use then in my SQL Statement powerd by SQLModel
```
class Order(SQLModel):
    __table_args__ = {"schema": "B"}

    id: Optional[int] = Field(default=None, primary_key=True)
    key: int
```

```
statement = select(Sample).join(Table, Sample.key == Order.key)
```

However, this seems not to work. Any help would be highly appreciated

### Operating System

Windows

### SQLModel Version

0.0.7

### Python Version

3.8.1

**Comment by phi-friday** [comment]
It works fine, at least in postgresql.
Try the following.

```python
select(<some column>, ...).select_from(
    join(
        <left_table>,
        <right_table>,
        and_(
            <join_condition>, ...
        ),
    )
)
```

**Comment by christianholland** [comment]
@phi-friday thanks for confirming that it should work like theoretically. In the end it turned out that I forgot to set `table=True` for the `Order` Model

**Comment by tiangolo** [comment]
Thanks for the help here @phi-friday ! 👏  🙇 

Thanks for reporting back and closing the issue @christianholland  👍
