### ISSUE TITLE
Inheriting UserMixin class from flask-login library on SQLModel model crashes the app 

### ISSUE THREAD

**Issue by km-monzurul-islam** [tiangolo/sqlmodel#476]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from flask import Flask
from sqlmodel import SQLModel, Field, create_engine
from flask_login import UserMixin

class Account(UserMixin, SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str
    scotia_id: str = Field(unique=True)
    email: str = Field(unique=True)
    password: str


engine = create_engine('sqlite:///site.db')
SQLModel.metadata.create_all(engine)

app = Flask(__name__)
if __name__ == '__main__':
    app.run(debug=True)
```

### Description

(project) ➜  project python test.py
Traceback (most recent call last):
  File "/home/johnny/project/test.py", line 5, in <module>
    class Account(UserMixin, SQLModel, table=True):
  File "/home/johnny/.local/share/virtualenvs/project-ABytqz7n/lib64/python3.10/site-packages/sqlmodel/main.py", line 322, in __init__
    config = getattr(base, "__config__")
AttributeError: type object 'UserMixin' has no attribute '__config__'

### Operating System

Linux

### Operating System Details

Fedora 36 Gnome Desktop

### SQLModel Version

0.0.8

### Python Version

Python 3.10.7

**Comment by byrman** [comment]
This pull request might solve your problem: https://github.com/tiangolo/sqlmodel/pull/256.

**Comment by byrman** [comment]
Related issues:
- https://github.com/tiangolo/sqlmodel/issues/254
- https://github.com/tiangolo/sqlmodel/issues/348

**Comment by km-monzurul-islam** [comment]
@byrman Thanks a lot!  I really like SQLModel didn't want to force myself to use sqlalchemy by itself

**Comment by tiangolo** [comment]
Thanks for the help @byrman ! ☕🍰

And thanks for coming back to close the issue @km-monzurul-islam ! 🤓
