### ISSUE TITLE
Is it normal unable to use autocomplete for SQLModel class field?

### ISSUE THREAD

**Issue by ggree1** [tiangolo/sqlmodel#483]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class Hero1(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None


class Hero2():
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None
```

### Description

I'm using Pycharm.
When I write code like,
`select(Hero1).where(Hero1.age > 35)`

I expect IDE to show field 'age' when I type 'Hero1.' but IDE autocomplete displays no fields of Hero1.
but with Hero2 (without SQLModel inherits), it surely works fine.

Is this normal or only my IDE problem?

### Operating System

Windows

### Operating System Details

windows 10
Pycharm 2022

### SQLModel Version

0.0.8

### Python Version

3.10.6

### Additional Context

![image](https://user-images.githubusercontent.com/48195768/199689175-f640c025-f656-4dc9-8add-2af34ecad07e.png)

![image](https://user-images.githubusercontent.com/48195768/199689241-87ebb206-c5ab-4d10-80d4-8794625877aa.png)

**Comment by ggree1** [comment]
already installed and no problem with pydantic model. Anyway it looks my IDE problem..  thanks.

**Comment by tiangolo** [comment]
It's probably that PyCharm still doesn't support dataclass_transform, that's a new standard in Python and it was adopted by Pydantic and SQLModel even before it was an official standard.

You can probably ask them to add support for it. 🤓

**Comment by linpan** [comment]
@tiangolo  I will report this to JetBrains

**Comment by ggree1** [comment]
Thanks @tiangolo, @linpan.
I'm closing this issue.

**Comment by tiangolo** [comment]
Thanks @linpan ! And thanks for coming back to close it @ggree1 ☕

**Comment by linpan** [comment]
@ggree1 @tiangolo   has already support  PyCharm 2022.2.3.   Fastapi and Pydantic will more power and productivity
![20221107-103733](https://user-images.githubusercontent.com/6077601/200215173-8a12941e-3d19-4635-920c-d3b5954dd44d.gif)

**Comment by ggree1** [comment]
@linpan Thanks for the clarification. Actually I'm a Java developer so I was using latest IntelliJ with python plugin which supports almost same as Pycharm. I guess the python plugin has not yet updated this funcionality.

**Comment by tiangolo** [comment]
Just a note, autocompletion for attributes would work even without support for dataclass_transform. What dataclass_transform would help with is autocompletion for parameters when creating a new instance of the class.

**Comment by hydenp** [comment]
Was there a solution to this issue? I am using Pycharm 2024.1.1 and still running into this issue :( @linpan it seems to be working for you..?

My user model is as follows

```python
class UserModel(UserBase, table=True):
    __tablename__ = "_user"
    id: int | None = Field(default=None, primary_key=True)
```

With the others looking much the same

Here is what Pycharm looks like

<img width="684" alt="Screenshot 2024-05-12 at 8 58 05 PM" src="https://github.com/tiangolo/sqlmodel/assets/63132164/0398137a-af5a-480d-9b1c-4fb3b52765ec">

**Comment by linpan** [comment]
still have. SQLAlchemy have not autocompletion ,when instance.

**Comment by HeiziND** [comment]
@hydenp 

I am experiencing exactly the same issue as you. I believe however that it is a problem with the pydantic plugin for pycharm.

To illustrate the issue, please see the below minimal example.  I'm too swamped to do it now, but you're welcome to raise it as issue there in their [repo](https://github.com/koxudaxi/pydantic-pycharm-plugin)

[code](https://pastebin.com/uUJTfmnB)
![image](https://github.com/tiangolo/sqlmodel/assets/55983003/57a098df-687c-4ccd-9cb6-114d8bfb74b8)

**Comment by hydenp** [comment]
@HeiziND i opened an issue on JetBrains here

https://youtrack.jetbrains.com/issue/PY-72886/No-autocomplete-with-SQLModel-when-interpreter-specified

If it is with the plugin, I will possibly look into raising it there.

The weird thing is that autocomplete works perfectly when the interpreter is removed from the project. See the above issue for an example of that.

**Comment by gbaian10** [comment]
I have the same issue.
I'm not sure if it's my personal problem or a problem with PyCharm itself.

**Comment by kssion** [comment]
I just raised a question today #1416 

sqlmodel/main.py:476

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/3f86ec85-a02d-4ac4-9145-6502683488c7" />

If `@__dataclass_transform__` is changed to `@dataclass_transform`, everything meets expectations
