### ISSUE TITLE
How to reference a foreign key in a table that is in a different (postgres) schema

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [tiangolo/sqlmodel#495]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
#
# Apologies, this is not a fully reproducible example, as 
# you will need to create a postgres database with schemas
# to reproduce fully.
#

import sqlmodel

engine = create_engine(os.getenv("PGURL"), echo=True)                                                                  

# Define a table in the postgres schema: schema_1

class Model1(sqlmodel.SQLModel, table=True):                                   
    metadata = sqlmodel.MetaData(schema="schema_1")                             
    id: int = sqlmodel.Field(default=None, primary_key=True)                     

# Define a table in the postgres schema: schema_2

class Model2(sqlmodel.SQLModel, table=True):                           
    metadata = sqlmodel.MetaData(schema="schema_2")                               
    id: int = sqlmodel.Field(default=None, primary_key=True)                    
    model1_id: int = sqlmodel.Field(default=None, foreign_key="schema_1.model1.id")

with Session(engine) as session:
    # Add a new instance of model1

    model1 = Model1()
    session.add(model1)
    session.commit()
    session.refresh(model1)

    # Try to add an instance of model2 referencing model1.id

    model2 = Model2(model1_id=model1.id)

    session.add(model2)
    session.commit()
    session.refresh(model2)

    # Print the annotation_set table

    statement = select(Model2)
    model2s = session.exec(statement).all()
    print(model2s)
```

### Description

* I'm defining models for a postgres database that someone else has created, using postgres schemas to organise the tables.
* I create a table `model1` and table `model2` which has a foreign key `model1.id`
* When I run the code above code I get the following error: 
  ```sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'model2.model1_id' could not find table 'shema_1.model1' with which to generate a foreign key to target column 'id'```
* I realise that `sqlmodel` is reading `schema_1.model1` as the full table name, but I can't work out how to point it at `schema_1`. Is this possible?

Many thanks :pray: 

### Operating System

Linux

### SQLModel Version

0.0.8

### Python Version

Python 3.8.10

**Comment by ivyleavedtoadflax** [comment]
In the end I was able to resolve this issue with the following:

```
import sqlmodel
from sqlalchemy import Column, Integer, ForeignKey

class Model1(sqlmodel.SQLModel, table=True):                                   
    metadata = sqlmodel.MetaData(schema="schema_1")                             
    id: int = sqlmodel.Field(default=None, primary_key=True)  

class model2(sqlmodel.SQLModel, table=True):
    metadata = sqlmodel.MetaData(schema="schema_2")
    id: int = sqlmodel.Field(default=None, primary_key=True)
    model1_id: int = Column(Integer(), ForeignKey("schema_1.model1.id"))
```

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

**Comment by mathieulebasic** [comment]
@tiangolo thanks so much for your work! Do you know if this issue has been addressed on the SQLModel wrapper or should we still use the sqlalchmey syntax for this ?

**Comment by Meepoljdx** [comment]
> @tiangolo thanks so much for your work! Do you know if this issue has been addressed on the SQLModel wrapper or should we still use the sqlalchmey syntax for this ?

this write way is fine for me

`
class WebhookRecieverGroupsLink(SQLModel, table=True):
    __tablename__ = "webhook_reciever_groups_link"
    webhook_id: uuid.UUID | None = Field(
        default=None, foreign_key='owl_alert_webhooks.id', primary_key=True, alias=""
    )
    receiver_groups_id: uuid.UUID | None = Field(
        default=None, foreign_key='owl_alert_receiver_groups.id', primary_key=True
    )


class ReceiverGroups(BaseModel, table=True):
    __tablename__ = 'owl_alert_receiver_groups'

    webhooks: list["Webhooks"] = Relationship(
        back_populates="receiver_group",
        link_model=WebhookRecieverGroupsLink)


class Webhooks(BaseModel, table=True):
    __tablename__ = 'owl_alert_webhooks'
    name: str = Field(
        nullable=False,
        description='The name of webhook',
        unique=True
    )
    enabled: bool = Field(
        default=True,
        description='Enable this webhook or not',
        index=True
    )
    receiver_group: list['ReceiverGroups'] = Relationship(
        back_populates="webhooks",
        link_model=WebhookRecieverGroupsLink)
`
