### ISSUE TITLE
"Update release note" is contaminating the git history

### ISSUE THREAD

**Issue by kingyue737** [tiangolo/sqlmodel#498]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# Ignore
```

### Description

Release note should be updated once before release, not after each commit. For example, you can achieve this by https://github.com/frinyvonnick/gitmoji-changelog. Currently it's hard to watch the git history.

![image](https://user-images.githubusercontent.com/40021217/201620219-4321bfa1-4239-42b8-b95c-a46c06637b71.png)

### Operating System

Windows

### SQLModel Version

Ignore

### Python Version

Ignore

**Comment by tiangolo** [comment]
Sorry, but I can't go and set up more CI stuff for this, there's a lot of things that need more urgent attention.

Given that, I'll pass on this request, but thanks for the interest. ☕
