### ISSUE TITLE
It is possible to create a class for selecting specific columns in a table?

### ISSUE THREAD

**Issue by omer-priel** [tiangolo/sqlmodel#499]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    age: Optional[int]
    field_1: Optional[str]
    field_2: Optional[str]
    field_3: Optional[str]
    field_4: Optional[str]
    field_5: Optional[str]

class UserMinimal:
    id: Optional[int]
    name: str
    age: Optional[int]

def select_users():
    with Session(engine) as session:
        users = session.exec(select(User)).all()
        print(*users, sep="\n")

def select_users_minimal():
    with Session(engine) as session:
        users = session.exec(select(UserMinimal)).all()
        print(*users, sep="\n")
```

### Description

It is possible to create a class for selecting specific columns in a table?

Issue #232 discusses how to select specific columns.
But, if I want to select specific columns lots of times in the application. The idea of class seems more suitable

### Operating System

Linux

### Operating System Details

Linux Mint

### SQLModel Version

0.0.8

### Python Version

Python 3.10.6

**Comment by tiangolo** [comment]
Thanks for the help here @meirdev ! 👏  🙇 

If that solves the original problem, then you can close this issue @omer-priel  ✔️

**Comment by omer-priel** [comment]
Thanks

**Comment by omer-priel** [comment]
last two questions,
I want to help SQLModel, but I haven't found a roadmap / bugs (exists only one), So how can I help?
In addition, exist type of "sandbox" application that uses all the features or like TDD the all the features tests and examples in the tests only?

**Comment by jpmckinney** [comment]
This is maybe worth adding to the documentation, since its many variations come up in #337 #232
