### ISSUE TITLE
Generate SQLModel table class from dictionary

### ISSUE THREAD

**Issue by Udayaprasad** [tiangolo/sqlmodel#508]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
`class CRFForm(CRFFormBase, table=True):
    patient_id: Optional[uuid.UUID] = Field(default_factory=uuid.uuid4,
                                        primary_key=True, nullable=False,
                                        title="Generate a random UUID4 - PK")
    patient_name: str = Field(nullable=False, title='patient_name',
                              description='patient_name', minlength=10, maxlength=50)
    age: int = Field(nullable=False, title='age', description='age', le=120)
    is_married: Optional[bool] = Field(default=True, title="is_married")`
```

### Description

Given the following input (for say).

`input_dict = {
    "table_name": "CRFForm",
    "columns": [
        {
            "name": "patient_id",
            "title": "",
            "description": "",
            "type": uuid.UUID,
            "default": uuid.uuid4(),
            "nullable": False,
            "primary": True
        },
        {
            "name": "patient_name",
            "title": "",
            "description": "",
            "type": str,
            "minlength": 10,
            "maxlength": 50,
            "nullable": False,
            "unique": True
        },
        {
            "name": "age",
            "title": "",
            "description": "",
            "type": int,
            "nullable": False,
            "le": 120
        },
        {
            "name": "is_married",
            "title": "",
            "description": "",
            "type": bool,
            "nullable": False
        }
    ]
}`

### Wanted Solution

output --->` Generate SQLModel class from the above dictionary by satisfying the table relations and constraints`

### Wanted Code

```python
`class CRFForm(CRFFormBase, table=True):
    patient_id: Optional[uuid.UUID] = Field(default_factory=uuid.uuid4,
                                        primary_key=True, nullable=False,
                                        title="Generate a random UUID4 - PK")
    patient_name: str = Field(nullable=False, title='patient_name',
                              description='patient_name', minlength=10, maxlength=50)
    age: int = Field(nullable=False, title='age', description='age', le=120)
    is_married: Optional[bool] = Field(default=True, title="is_married")`
```

### Operating System

Linux, Windows, macOS

### Operating System Details

Windows 10 Laptop and tianglo 3.9 slimbust image

### SQLModel Version

0.8

### Python Version

3.9

**Comment by meirdev** [comment]
You need to use `type` to create a new table dynamically:

```python
import uuid
from typing import Optional, Type

from sqlmodel import SQLModel, Field, create_engine, Session


input_dict = {
    "table_name": "CRFForm",
    "columns": [
        {
            "name": "patient_id",
            "type": Optional[uuid.UUID],
            "default_factory": uuid.uuid4,
            "primary_key": True,
        },
        {
            "name": "patient_name",
            "type": str,
            "nullable": False,
        },
    ]
}

def create_table_from_dict(input_dict) -> Type[SQLModel]:
    annotations = {
        col["name"]: col["type"] for col in input_dict["columns"]
    }

    columns = {
        col["name"]: Field(**{c: col[c] for c in col if c not in ("name", "type")}) for col in input_dict["columns"]
    }

    return type(
        input_dict["table_name"],
        (SQLModel,),
        {
            "__annotations__": annotations,
            **columns,
        },
        table=True,
    )


# Test

t1 = create_table_from_dict(input_dict)

engine = create_engine(
    "sqlite:///",
    echo=True,
)

with Session(engine) as session:
    SQLModel.metadata.create_all(engine)

"""
CREATE TABLE crfform (
        patient_id CHAR(32) NOT NULL, 
        patient_name VARCHAR NOT NULL, 
        PRIMARY KEY (patient_id)
)
"""
```

**Comment by Udayaprasad** [comment]
@meirdev ,

Thank you for your prompt response.  Our idea behind using the creation of this dynamic table is to perform the auto upgrade of the table using alembic migration. Our schema is so dynamic, will change more often.

Is there any way to supply boundary conditions, such as for
 ```
str : minlength, maxlength,
int: le, gt
```

**Comment by meirdev** [comment]
All arguments of the `Field` function can be defined:

```python
{
    "name": "patient_name",
    "type": str,
    "nullable": False,
    "min_length": 10,
    "max_length": 50,
},
{
    "name": "age",
    "type": int,
    "nullable": False,
    "le": 120,
}
```

To support foreign key relationships, you should continue with this idea with the `Relationship` function.

**Comment by Udayaprasad** [comment]
Seems foreign_key  `team_id: Optional[int] = Field(default=None, foreign_key="team.id")` should suffice the general relations. As you said we need to use the `Relationship ` function like the `Field` function to achieve the back population of data and link_table scenarios.
I will mark this ticket as done. Thank you for your help.

**Comment by Udayaprasad** [comment]
Added the code here.

https://github.com/Udayaprasad/dynamic_sqlmodel_creator

**Comment by raffaem** [comment]
> Added the code here.
> 
> https://github.com/Udayaprasad/dynamic_sqlmodel_creator

The page is dead
