### ISSUE TITLE
Translating between models for the Multiple Models pattern, to store private data

### ISSUE THREAD

**Issue by nward** [tiangolo/sqlmodel#527]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class CustomerBase(SQLModel):
    name: str

class Customer(CustomerBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    domains: List["Domain"] = Relationship(back_populates="customer")

class CustomerCreate(CustomerBase):
    pass

class CustomerRead(CustomerBase):
    id: int



class DomainBase(SQLModel):
    name: str

class Domain(DomainBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

    customer_id: int = Field(foreign_key="customer.id")
    customer: Customer = Relationship(back_populates="domains")

class DomainCreate(DomainBase):
    pass

class DomainRead(DomainBase):
    id: int



@router.post("/", response_model=DomainRead, status_code=201)
async def create_domain(domain: DomainCreate, session: AsyncSession = Depends(get_session)):
    """Create a new domain"""
    domain_full = Domain(**domain.dict())

    # FIXME: Set customer_id to any old customer
    result = await session.execute(select(Customer))
    customer = result.scalars().first()
    domain_full.customer = customer
    session.add(domain_full)
    await session.commit()
    return domain_full
```

### Description

I am following the Multiple Models pattern, using SQLModel with FastAPI.

In my example, I have two models, a Domain, and a Customer, along with the xxRead, xxCreate, xxBase etc.
Customer has many Domains.
Domains has one Customer.

Note that the example works - I am trying to find out if this is the best way to do this, or, if there is a more elegant way that I have missed in the documentation.

Domain can be created by customers.
Customer is intended to be internal-only, and never visible to users. The Customer <=> Domain relationship is added by logic in the server, the user creating Domain does not need to pass customer_id. In the above example, it is just taking the first one in the database - which is obviously not the final implementation 😄 

Because DomainCreate does not have `customer` or `customer_id` attributes, I need to convert  my `DomainCreate` object to a `Domain` object, so that I can assign a `Customer` to it. I am doing this with:
```python
domain_full = Domain(**domain.dict())
```

Is this the best way to go about doing this? Is there a better way to design this?

This feels like it is missing from the Multiple Models documentation, so I am happy to contribute the best approach to the documentation.

### Operating System

Linux

### SQLModel Version

0.0.8

### Python Version

3.11.1

**Comment by nward** [comment]
You know what, after writing this all down and going for a walk, it occurs to me that this happens with Pydantic as well, and is described here: https://fastapi.tiangolo.com/tutorial/extra-models/

Given that, I think this can be closed - Very sorry for the noise!!

**Comment by antont** [comment]
There's also `from_orm` in SQLModel, though, and it's featured in the extra model docs here:

```
@app.post("/heroes/", response_model=HeroRead)
def create_hero(hero: HeroCreate):
    with Session(engine) as session:
        db_hero = Hero.from_orm(hero)
        session.add(db_hero)
```

I've been using it, but don't know the difference with the pydantic dicts biz (if there's any, I've assumed something similar).

https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/
