### ISSUE TITLE
[Querying] negating `Model.boolean` in `where()` 

### ISSUE THREAD

**Issue by Pk13055** [tiangolo/sqlmodel#534]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import select, Field, Session, SQLModel, create_engine


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    test: bool
    name: str
    secret_name: str
    age: Optional[int] = None


hero_1 = Hero(name="Deadpond", test=False, secret_name="Dive Wilson")

engine = create_engine("sqlite:///database.db")


SQLModel.metadata.create_all(engine)

with Session(engine) as session:
    session.add(hero_1)
    session.commit()
    query = select(Hero).where(Hero.test)  # FIXME: this has to be `not Hero.test`
    heros = session.execute(query).all()
    print(heros)
```

### Description

- Create model with `bool` field
- Query `not field` in `select`
- Throws error OR evaluates to `False` instead of generating `WHERE` clause

### Operating System

macOS

### SQLModel Version

0.0.8

### Python Version

Python 3.10.9

**Comment by meirdev** [comment]
You can simply do:

```python
Hero.test == False
```

or use `not_`:

```python
from sqlalchemy import not_
not_(Hero.test)
```

A list of all operators: https://docs.sqlalchemy.org/en/20/core/operators.html

**Comment by Pk13055** [comment]
`not_` seems nice(r), thanks!
