### ISSUE TITLE
Implementation for no sql 

### ISSUE THREAD

**Issue by video-online** [tiangolo/sqlmodel#55]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
no code
```

### Description

sql is good but do you know any implemention for no sql ??!

### Wanted Solution

no code

### Wanted Code

```python
no code
```

### Operating System

Linux, Windows, macOS, Other

### SQLModel Version

no version

### Python Version

any version

**Comment by cbeauhilton** [comment]
https://github.com/tiangolo/sqlmodel/issues/63#issuecomment-916632210

Much NoSQL functionality can be had with json fields in postgres/SQLite.
