### ISSUE TITLE
How to add current date time by default on a table declaration?

### ISSUE THREAD

**Issue by fraddygil** [tiangolo/sqlmodel#594]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

how to add a field in the table with the current date by default?

**Comment by antont** [comment]
We've been doing it like this

`created_at: datetime = Field(default_factory=lambda: datetime.now())`

**Comment by FilipeMarch** [comment]
I do the same as @antont but without the `lambda`
```python
from sqlmodel import SQLModel, Field
import datetime


class Article(SQLModel, table=True):
    created_at: datetime.datetime = Field(
        default_factory=datetime.datetime.utcnow,
    )
```

**Comment by antont** [comment]
lol I don't know why we had the useless lambda, i guess some mindless copy-paste, thanks, will get to clean those up.

**Comment by firecube-oss** [comment]
This is the cleanest way I have found to do it 

**core_models.py**

```
class SimpleIDModel(BaseModel):
    id: int


class UUIDIDModel(BaseModel):
    id: UUID = Field(default_factory=uuid4)


class TimestampModel(BaseModel):
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime]


class EventTimestamp(BaseModel):
    occured_at: Optional[datetime]
```
**consuming.py** 

```
class Service(SimpleIDModel, TimestampModel, table=True):
    name: str = Field(nullable=False)
    description: str = Field(nullable=False)
```

I think having opinionated timestamping might not work. 

Some people might regard update_at as when a new version of the record was created rather than when the record is updated later on

**Comment by FilipeMarch** [comment]
This is how I use `updated_at`:

```python
from sqlmodel import SQLModel, Column, Field
from sqlalchemy import DateTime, func
from typing import Optional
import datetime


class Article(SQLModel, table=True):
    created_at: datetime.datetime = Field(
        default_factory=datetime.datetime.utcnow,
    )
    updated_at: Optional[datetime.datetime] = Field(
        sa_column=Column(DateTime(), onupdate=func.now())
    )
```

> Some people might regard update_at as when a new version of the record was created rather than when the record is updated later on

Personally I believe this does not make much sense. 
- When the record is created at 5PM, it was created_at 5PM. 
- When the record is updated at 7PM, it was updated_at 7PM.

**Comment by antont** [comment]
> Just going to throw this out there - created at / updated at / soft deleted at are really common patterns and there might be a bit of value to just make them first class features

How would you do it? Maybe a mixin in some library module, that one can use to add features to base SQLModel?

**Comment by JamesHutchison** [comment]
Yes, I think a mixin might work. I do think it's worth having a discussion how created at / updated at / deleted at would fit with created by / updated by / deleted by (so user IDs, which may be an integer or string type) as well as versioned entities (does created / updated just get replaced with "updated", and "created" is implicit with version 1?)

**Comment by Pietzaalberg** [comment]
It's common to delegate generating timestamps to the database rather than generating them in Python. Much like @FilipeMarch is showing in the `update_at` column. 

In that case you would set the [server_default](https://docs.sqlalchemy.org/en/13/core/defaults.html#server-invoked-ddl-explicit-default-expressions) attribute on the column. In the case of sqlalchemy it would look like this:
`time = db.Column(db.Time, server_default=sqlalchemy.func.now())`

I agree it's worth having a firstclass feature for this.

**Comment by rafalkrupinski** [comment]
Is the solution in https://github.com/tiangolo/sqlmodel/issues/594#issuecomment-1578962030 the answer? Can the issue be closed?

**Comment by mj2068** [comment]
> The advantage of this is I don’t need to refer to an actual sa_column, and using CURRENT_TIMESTAMP adheres to ansi sql standards

wow, amazing, this is works pretty good with alembic's --autogenerate
```
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
```

**Comment by danielqba** [comment]
This can be closed.

**Comment by PrinciMixtiy** [comment]
> lol I don't know why we had the useless lambda, i guess some mindless copy-paste, thanks, will get to clean those up.

`default_factory=` need a callable, so you need to add `lambda` if you add parentheses at the end of `datetime.now()`

**Comment by rafalkrupinski** [comment]
```py
default_factory=datetime.now
```

**Comment by thingsally** [comment]
It's so weird that ModelSQL docs don't mention anything about it....here there are  10+ various code suggestions but no standard way to define created_at and updated _at... Also why to define all in each models?  That's not the key purpose of ModelSQL???

I tried by abstraction but there were too many errors of time, timezone...created_at column already exists when I make a relationship.....

Can creator address or clarify this issue. Or we are Miss something.

**Comment by rlimaeco** [comment]
this is something that should be on the core features of SQLModel, not just let everyone do by your own, and as @thingsally said all the abstraction results in more problems. I'm trying so hard to use this awesome project that made my code way cleaner, but when I started to deal with timestamps that hurts a lot

**Comment by keni2002** [comment]
```
from datetime import datetime, timezone
from sqlmodel import Field

created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
```

**Comment by keni2002** [comment]
> default_factory

created_at: datetime = Field(default=datetime.now)

**Comment by jstpierre-sirix** [comment]
In case this is of any help, here is how I have implemented automatic `created_at` and `updated_at`. For some reason I had to take a more complicated route because `onupdate` seems to have no effect at all at least in `0.0.24` which is today's latest.

Note: Alembic will automatically generate migrations and include proper server metadata like so:

```python
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    # ### end Alembic commands ###
```

#### Mixin to include in every model using automatic timestamp

```python
from datetime import datetime, timezone
from typing import Any, ClassVar, Dict, Type, TypeVar

from sqlalchemy import Column, DateTime, event, func
from sqlmodel import Field

T = TypeVar("T", bound="Timestampable")


class Timestampable:
    """
    A mixin that adds timestamp functionality to SQLModel classes.
    """

    created_at: datetime = Field(sa_column=Column(DateTime(), server_default=func.now(), nullable=False))
    updated_at: datetime = Field(sa_column=Column(DateTime(), server_default=func.now(), nullable=False))

    _registered_classes: ClassVar[Dict[str, bool]] = {}

    @classmethod
    def __init_subclass__(cls: Type[T], **kwargs: Any) -> None:
        super().__init_subclass__(**kwargs)

        # Only register once per class
        if cls.__name__ not in Timestampable._registered_classes:
            event.listen(cls, "before_update", Timestampable._before_update)
            Timestampable._registered_classes[cls.__name__] = True

    @staticmethod
    def _before_update(mapper, connection, target):
        target.updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

```

And then all you got to do is add the mixin to your models:

```diff
- class User(SQLModel, table=True):
+ class User(SQLModel, Timestampable, table=True):
```

**Comment by adrianovieira** [comment]
Hi Folks!
Unfortunately, none of the above-mentioned workarounds works to create the **`updated_at`** column correctly.

`alembic revision --autogenerate -m "Hero: create table"`

Alembic: 1.17.2
SQLModel: 0.0.27
SQLAlchemy: 2.0.44
PostgreSQL psycopg[binary, pool]: 3.2.13

<details>
<summary>Hero SQLModel</summary>

```python
class Hero(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)

    created_at: datetime = Field(
        default=func.now(),
        sa_column=Column(
            DateTime(timezone=True),
            server_default=func.now(),
        ),
    )

    updated_at: datetime = Field(
        default=func.now(),
        sa_column=Column(
            DateTime(timezone=True),
            server_default=func.now(),

            # It doesn't matter if we use both or one of the parameters below;
            # it results in the same "wrong migration" script. 
            server_onupdate=func.now(), onupdate=func.now(),
        ),
        # # And even this one doesn't work.
        # sa_column_kwargs={
        #     "server_default": func.now(),
        #     "server_onupdate": func.now(),
        #     "onupdate": func.now(),
        # },
    )
```
</details>

Alembic results  
```python
def upgrade() -> None:
    """ Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
```

Expected behaviour is as follows:

```python
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),

``` 

Would you happen to have any other tips to give?

**Comment by jackmpcollins** [comment]
@adrianovieira My understanding is that `server_onupdate` is not supported by postgres, and `onupdate` is used when building the query so does not get included in migrations.

Here's how I'm doing it (simplified) in regular SQLAlchemy, which should be easy to translate to SQLModel, and appears to have the desired behavior.

```python
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
)

class Base(DeclarativeBase):
    pass

class TimestampedModel(Base):
    __abstract__ = True

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        # server_onupdate is not supported by postgres
        onupdate=func.now(),
    )
```
