### ISSUE TITLE
How to use Mixins?

### ISSUE THREAD

**Issue by lovetoburnswhen** [tiangolo/sqlmodel#70]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class TimeStampMixin:
    """Provides last created/modified timestamps"""

    created_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime,
            default=datetime.utcnow,
            nullable=False,
        )
    )

    updated_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime,
            default=datetime.utcnow,
            onupdate=datetime.utcnow,
        )
    )


class MyModel(SQLModel, TimestampMixin, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
```

### Description

- Utilize mixins that don't necessarily need to subclass `SQLModel`
  - Perhaps something that resembles `@declarative_mixin` from SQLAlchemy?

The above example errors with:
```
AttributeError: type object 'TimeStampMixin' has no attribute '__config__'
```

### Operating System

Linux

### SQLModel Version

0.0.4

### Python Version

3.9.0

**Comment by elben10** [comment]
Try this out

```python
from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from sqlmodel import SQLModel, Column, DateTime, Field, Session, create_engine, select

        
class TimeStampMixin(BaseModel):
    created_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime,
            default=datetime.utcnow,
            nullable=False,
        )
    )

    updated_at: Optional[datetime] = Field(
        sa_column=Column(
            DateTime,
            default=datetime.utcnow,
            onupdate=datetime.utcnow,
        )
    )
    


class MyModel(SQLModel, TimeStampMixin, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
        
engine = create_engine("sqlite:///database.db")
SQLModel.metadata.create_all(engine)

with Session(bind=engine) as session:
    session.add(MyModel(name="A Name"))
    session.commit()
```

**Comment by lovetoburnswhen** [comment]
> Try this out
> 
> ```python
> from datetime import datetime
> from typing import Optional
> 
> from pydantic import BaseModel
> from sqlmodel import SQLModel, Column, DateTime, Field, Session, create_engine, select
> 
>         
> class TimeStampMixin(BaseModel):
>     created_at: Optional[datetime] = Field(
>         sa_column=Column(
>             DateTime,
>             default=datetime.utcnow,
>             nullable=False,
>         )
>     )
> 
>     updated_at: Optional[datetime] = Field(
>         sa_column=Column(
>             DateTime,
>             default=datetime.utcnow,
>             onupdate=datetime.utcnow,
>         )
>     )
>     
> 
> 
> class MyModel(SQLModel, TimeStampMixin, table=True):
>     id: Optional[int] = Field(default=None, primary_key=True)
>     name: str
>         
> engine = create_engine("sqlite:///database.db")
> SQLModel.metadata.create_all(engine)
> 
> with Session(bind=engine) as session:
>     session.add(MyModel(name="A Name"))
>     session.commit()
> ```

That works! This also enables a `Generic[_T]` base class

**Comment by klav-zhaw** [comment]
Why do we need to extend the Mixins from pydantic BaseModel and not SQLModel? Or is both possible? Also, with SQLModel, the definition would be simpler:
`class TimeStampMixin(SQLModel):
    created_at: Optional[datetime] = Field(default=datetime.utcnow(), nullable=False)
    updated_at: Optional[datetime] = Field(default_factory=datetime.utcnow, nullable=False)
`
