### ISSUE TITLE
Non-optional property with default value is not translated to a non-nullable field in sqlalchemy

### ISSUE THREAD

**Issue by van51** [tiangolo/sqlmodel#76]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional
from sqlmodel import SQLModel, Field, create_engine


class Test(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    a: str
    b: Optional[str] = None
    c: str = Field(default="Hey")
    d: str = "hey"
    
sqlite_url = ""  # define a path here
engine = create_engine(sqlite_url, echo=True)
SQLModel.metadata.create_all(engine)
```

### Description

The above code example issues the following create table sql command:
```sql
CREATE TABLE test (
	id INTEGER, 
	a VARCHAR NOT NULL, 
	b VARCHAR, 
	c VARCHAR, 
	d VARCHAR, 
	PRIMARY KEY (id)
)
```
whereas I would expect columns `c` and `d` to be marked as `NOT NULL` as well. 
I think the documentation also points to my point of view as stated [here](https://sqlmodel.tiangolo.com/tutorial/create-db-and-table/?h=optional#optional-fields-nullable-columns).

### Operating System

Linux

### SQLModel Version

0.0.4

### Python Version

3.8.5

**Comment by ChielWH** [comment]
Shouldn't it result in:
```sql
CREATE TABLE test (
	id INTEGER, 
	a VARCHAR NOT NULL, 
	b VARCHAR, 
	c VARCHAR DEFAULT "hey" NOT NULL,
	d VARCHAR DEFAULT "hey" NOT NULL, 
	PRIMARY KEY (id)
)
```
?

**Comment by skykasko** [comment]
@ChielWH: No, default values provided in SQLModel/SQLAlchemy columns through the [`default`][1] parameter are invoked client-side by SQLAlchemy before data is passed to the database, and are not part of the table's DDL definition. To create a server-side default value that is part of the table's definition, the [`server_default`][2] parameter must be used instead.

See: <https://docs.sqlalchemy.org/en/14/core/defaults.html>.

[1]: https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Column.params.default
[2]: https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Column.params.server_default

**Comment by tiangolo** [comment]
Thanks for the detailed report and fix @van51! :bow: :cake:
