### ISSUE TITLE
How to order_by descending?

### ISSUE THREAD

**Issue by SunsetOrange** [tiangolo/sqlmodel#8]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
statement = select(Record).order_by(Record.record_id)
records = session.exec(statement).all()
records.reverse()
```

### Description

I'm trying to find a way to perform a select order_by in descending order. I've been performing descending orders in SQLAlchemy with the following line.
select_operation = record_table.select().order_by(record_table.columns.record_id.desc())

I can't see anywhere in the documentation or within intellisense for reversing the sort order. As this project is less than a day old, am I jumping the shark here and it isn't implemented yet, or am I missing something?

### Operating System

Linux

### Operating System Details

Fedora 34

### SQLModel Version

0.0.3

### Python Version

3.9.6

**Comment by synic** [comment]
```python
select(Record).order_by(Record.record_id.desc())
``|

**Comment by peterHoburg** [comment]
What @synic said. Here is the link to the relevant SQLAlchemy parent doc. 
https://docs.sqlalchemy.org/en/14/tutorial/data_select.html#tutorial-order-by

**Comment by SunsetOrange** [comment]
My mistake. Thanks for the help synic.

**Comment by sarimmehdi** [comment]
why is the autocomplete not working for desc here?

**Comment by j6e** [comment]
> why is the autocomplete not working for desc here?

see #259
