### ISSUE TITLE
Field cannot autocompletion when its a SQLModel

### ISSUE THREAD

**Issue by zhaowcheng** [tiangolo/sqlmodel#890]
### Privileged issue

- [ ] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

`Sorry for create this issue without permission, because this question has been in the discussion area for a week but no one has paid attention to it.`

### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from sqlmodel import SQLModel
from typing import Optional

class ModelNode(SQLModel):
    id: int
    name: str

class Node:
    id: int
    name: str

class Cluster(SQLModel):
    model_node: Optional[ModelNode] = None
    node: Optional[Node] = None
```

### Description

Cluster.node. can autocompletion, but Cluster.model_node. cannot

### Operating System

macOS

### Operating System Details

IDE: vscode

### SQLModel Version

0.0.16

### Python Version

3.10.5

### Additional Context

![image](https://github.com/tiangolo/sqlmodel/assets/4382523/48c09870-e5e7-4322-85c3-c326765a7bc7)

![image](https://github.com/tiangolo/sqlmodel/assets/4382523/5e9f25fd-b47e-41bc-9e2e-1a783f506f03)

**Comment by asacristani** [comment]
@zhaowcheng  If you create a new object from this class, the autocompletion works:
<img width="798" alt="image" src="https://github.com/tiangolo/sqlmodel/assets/8972362/82bb875e-5aa7-4eff-97da-6dd1f328548c">
Also if you try to access to the property directly:
<img width="592" alt="image" src="https://github.com/tiangolo/sqlmodel/assets/8972362/17e66a69-894b-49ab-a8a7-fd0f71ad6ff1">

So not sure what is happening in your end, (maybe any VS code configuration is missing?)

**Comment by zhaowcheng** [comment]
@asacristani , thank you for your answer.

I downgraded pydantic from `v2` to `v1` and it worked. 

Is this a bug in sqlmodel?

**Comment by waketzheng** [comment]
Autocomplete worked for me with latest version of sqlmodel and pydantic2.5.3 (Python3.11/Pycharm)
<img width="901" alt="image" src="https://github.com/tiangolo/sqlmodel/assets/35413830/f45e62e0-962a-4f5c-a70d-f161461f342f"> 

<img width="408" alt="image" src="https://github.com/tiangolo/sqlmodel/assets/35413830/875e5ad5-6228-4d01-82ae-c149553828dc">

**Comment by zhaowcheng** [comment]
@waketzheng 
yes, `pycharm `can autocomplete when pydantic is `v2`, but `vscode` cannot.

**Comment by dipsx** [comment]
> @waketzheng yes, `pycharm `can autocomplete when pydantic is `v2`, but `vscode` cannot.

same issue in vscode

**Comment by Abeautifulsnow** [comment]
I usually develop on WSL1 for windows. And the autocompletion functionality works fine in my vscode.
![image](https://github.com/tiangolo/sqlmodel/assets/28704977/e3c2c559-65f7-4c7b-b98a-af4ee545f0e6)

And my packages infos are below:
```bash
pydantic          2.7.1    Data validation using Python type hints
sqlmodel          0.0.18   SQLModel, SQL databases in Python, designed for simplicity, compatibility, and robustness.
```

**Comment by JoseMMerida** [comment]
> I usually develop on WSL1 for windows. And the autocompletion functionality works fine in my vscode. ![image](https://private-user-images.githubusercontent.com/28704977/329767757-1abf6088-a26c-408e-b966-7c3508ff819d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDE4NjksIm5iZiI6MTcxNzQwMTU2OSwicGF0aCI6Ii8yODcwNDk3Ny8zMjk3Njc3NTctMWFiZjYwODgtYTI2Yy00MDhlLWI5NjYtN2MzNTA4ZmY4MTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA3NTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZDMwYjk2YzU3YTRhMGMyZjBkYTdkMDk4ODE0OTlmMTdkNTc5NzBkODA4MWU2NTFiYjM4M2Q2YjdhNDMzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._DnvXk0vA373GHvVJhGXsGOMcAEQBcmTAlZ6Xib8_S4)
> 
> And my packages infos are below:
> 
> ```shell
> pydantic          2.7.1    Data validation using Python type hints
> sqlmodel          0.0.18   SQLModel, SQL databases in Python, designed for simplicity, compatibility, and robustness.
> ```

After updating to the versions that you mention it got fixed! 

On sqlmodel 0.0.16 + SQLALchemy 2.0.28 it was not working!

**Comment by linpan** [comment]
Field cannot autocompletion when its a SQLModel
